### ISSUE TITLE
Let's get some Vagrant!

### ISSUE THREAD

**Issue by rlowe** [outbrain/orchestrator#100]
Hey Shlomi,

@shuhaowu mentioned in https://github.com/outbrain/orchestrator/issues/78 that he’s putting together a fork with Vagrant machines that can be used for testing (https://github.com/shuhaowu/orchestrator/tree/vagrant).  I’ve also got a Vagrant branch at https://github.com/rlowe/orchestrator/tree/rlowe-vagrant, with slightly different requirements and goals than @shuhaowu (CentOS vs. Debian, 4 vs 3 hosts, etc).  Clearly this is something that lots of folks would benefit from.  Indeed, it would make our testing much cleaner.  As such, I’d like to do whatever I can to facilitate getting this functionality merged.  My thoughts about requirements:

- Support both CentOS and Ubuntu
- Sets up one “admin” node and four MySQL nodes
- Set up replication (Master<->Master, each with a replica)
- Make the source code available in /vagrant within the VM

I don’t necessarily want to do anything fancier than that.  Folks (i.e. me) can build Orchestrator and set it up in our own special ways once it’s there.

Thoughts?  Toss me some feedback about what I have versus what you want and in exchange I’ll give you a PR :-D

**Comment by shlomi-noach** [comment]
Hi Ryan,

So right now I'm using mysqlsandbox, and Vagrant is good to get.
Since I don't have experience with Vagrant, I'm not sure in what sense your implementation will be different from that of others (OK 4 vs 3, CentOS vs Debian; what else? RBR vs SBR? GTID vs Non-GTID?).
Can this be configurable?
What would a PR look like? (number of files + size)

tnx

**Comment by rlowe** [comment]
Hey Shlomi,

A PR would basically consist of one Vagrant file in the root directory, plus a new directory with a handful of build scripts.  In order to make it easier to test the many different configurations, one approach I can take is to create template files for /etc/my.cnf that can be changed before running `vagrant up`.  That PR would look something like: https://github.com/outbrain/orchestrator/compare/master...rlowe:rlowe-vagrant

**Comment by shlomi-noach** [comment]
I'm happy to accept such a PR. Will there always be only one Vagrant file in the root directory or would there be one Vagrant file for each type of Vagrant setup? Also what would be the impact of a 2nd setup? More files in /vagrant?
I'm asking as I would like this to be clean and organized before all hell breaks lose.

**Comment by rlowe** [comment]
https://github.com/outbrain/orchestrator/pull/103

To answer your question, any vagrant changes that we want to do should be limited to:

.gitignore
Vagrantfile
vagrant/

If somebody wants to use a different Vagrantfile, they can set their VAGRANT_VAGRANTFILE environmental variable (http://docs.vagrantup.com/v2/other/environmental-variables.html).

It is in my medium-term thoughts to support additional topologies, versions, and MySQL configurations but getting this basic infrastructure in place will allow us to make those decisions in an informed manner.

**Comment by shlomi-noach** [comment]
Thank you. Closing this issue as per https://github.com/outbrain/orchestrator/pull/103
