### ISSUE TITLE
Provide a cluster event history page linked from the main cluster page.

### ISSUE THREAD

**Issue by sjmudd** [outbrain/orchestrator#105]
When using the GUI you may be looking at a cluster using a url such as:

https://orchestrator.example.com/web/cluster/cluster.example.com:3306.

This gives a nice page showing the master and slaves under it.
Also currently you get a list of "recent alerts" which are relevant to this cluster, such as:

This cluster just recently recovered from AllIntermediateMasterSlavesFailingToConnectOrDead. It may still take some time to rebuild topology graph.
somehost.example.com:3306 has just recently been promoted as result of AllIntermediateMasterSlavesFailingToConnectOrDead. It may still take some time to rebuild topology graph.

So you get the "recent" history.

It would be useful to be able to look back (at the cluster) and see all related events.
Perhaps this could be added to the "i" icon (cluster event history) which if clicked would take you to such a list of events.

**Comment by shlomi-noach** [comment]
done, from the "i" sidebar on cluster page; just links to filtered cluster's recovery history, no fancy popups
