### ISSUE TITLE
Make "recent event notifications" clickable to go to details of that event

### ISSUE THREAD

**Issue by sjmudd** [outbrain/orchestrator#106]
When using the GUI you may be looking at a cluster using a url such as:

https://orchestrator.example.com/web/cluster/cluster.example.com:3306.

This gives a nice page showing the master and slaves under it.
Also currently you get a list of "recent alerts" which are relevant to this cluster, such as:

This cluster just recently recovered from AllIntermediateMasterSlavesFailingToConnectOrDead. It may still take some time to rebuild topology graph.
somehost.example.com:3306 has just recently been promoted as result of AllIntermediateMasterSlavesFailingToConnectOrDead. It may still take some time to rebuild topology graph.

The text in bold such as "AllIntermediateMasterSlavesFailingToConnectOrDead" could be clickable, allowing us to go to logging which describes in details the issue that occurred and what actions took place. It would be nice to see such information as you can then diagnose very quickly what the problem was and what actions were taken without leaving the gui.

**Comment by shlomi-noach** [comment]
done; just links to filtered cluster's recovery history, no fancy popups
