### ISSUE TITLE
Show server_uuid on servers that have such a value

### ISSUE THREAD

**Issue by sjmudd** [outbrain/orchestrator#109]
For MySQL 5.6+ there's a server_uuid variable. This must be unique for each server amongst a master and it's slaves.
It might be convenient to show this value when reporting information about a MySQL server in Orchestrator, even if this value is not available in MariaDB.
The other value, server_id is shown.

**Comment by shlomi-noach** [comment]
server_uuid is already being collected. I'll add it to modal dialog

**Comment by shlomi-noach** [comment]
done
