### ISSUE TITLE
Reseting slave does not work by default

### ISSUE THREAD

**Issue by leoleovich** [outbrain/orchestrator#111]
Hey:)
I did as it written here 
https://github.com/outbrain/orchestrator/wiki/Orchestrator-Manual#grant-access-to-orchestrator-on-all-your-mysql-servers

And now when I click "Reset slave" I got an error:
Error 1227: Access denied; you need (at least one of) the RELOAD privilege(s) for this operation

Installed version is - orchestrator=1:1.4.415, os DEBIAN

**Comment by shlomi-noach** [comment]
Thank you for pointing this out. I will update the manual

**Comment by shlomi-noach** [comment]
updated manual
