### ISSUE TITLE
provide some sort of quiet logging for command line usage

### ISSUE THREAD

**Issue by sjmudd** [outbrain/orchestrator#112]
The orchestrator cli is good and concise and very unix like. that is it doesn't say almost anything by default. That seems good but for a paranoid DBA no output is rather scary as you're never sure what you want.

There is a --debug option which provides a lot more detail but personally I'd prefer some sort of functional logging which has an in between verbosity which tells you functionally what orchestrator will do, and confirm the operation has succeeded.

Something like:

2015-09-30 16:02:07 INFO ChangeMasterTo: Change master on {Hostname:somehost.example.com Port:3306} from: &{Hostname:old-master.example.com Port:3306} to: &{Hostname:new-master.example.com Port:3306}, &{LogFile:binlog.000062 LogPos:60448572 Type:0}. GTID: false

and a line to confirm if the operation succeeded or failed.

If this (sort of) operation is repeated on several slaves at once complete silence (for some time) can be a bit disconcerting, whereas a list of intended actions and their completion status would make a DBA feel much better.

Also for clarity of logging {Hostname:somehost.example.com Port:3306}  is probably best to just write as somehost.example.com:3306. Remove the goism and show a more DBA friendly output :-)

**Comment by shlomi-noach** [comment]
"--verbose" is available, that I believe shows what you are looking for. If
it does not - it should, and so we should control which messages are
"verbosed" and which are "debug".

**Comment by shlomi-noach** [comment]
Re: `{Hostname:somehost.example.com Port:3306}`, this is certainly possible; I will need to search&replace quite a few places; this may take a while.

**Comment by dgryski** [comment]
Just add a String() method to whichever struct type that is; %v will use that instead.

**Comment by shlomi-noach** [comment]
ack, done (not pushed yet)
