### ISSUE TITLE
Hide replication from slow queries

### ISSUE THREAD

**Issue by leoleovich** [outbrain/orchestrator#119]
I have already many clusters and servers in orchestrator and long-queries page became unreadable.

<img width="413" alt="2015-10-30 16 32 49" src="https://cloud.githubusercontent.com/assets/4749052/10850080/0ce4845a-7f24-11e5-84a3-e4aa94868f85.png">

Would be nice to have some detection of replication thread and possibility not to see it.
Thank you.

**Comment by shlomi-noach** [comment]
Will filter out processes WHERE:
```
    USER = 'system user'
    OR COMMAND = 'Binlog Dump'
```

**Comment by shlomi-noach** [comment]
Wait... This is already the case.
Is the screenshot you attached the entire output?
Can you paste output of `/api/long-queries`?

**Comment by leoleovich** [comment]
```
[{"InstanceHostname":"aw-db01-t-ds-wallet","InstancePort":3306,"Id":15,"User":"rep","Host":"10.18.16.15:49972","Db":"","Command":"Binlog Dump GTID","Time":414084,"State":"Master has sent all binlog to slave; waiting for binlog to be up","Info":"","StartedAt":"2015-11-11 15:01:34"},{"InstanceHostname":"af-db02-t-ds-wallet","InstancePort":3306,"Id":11,"User":"rep","Host":"10.18.16.14:52627","Db":"","Command":"Binlog Dump GTID","Time":414003,"State":"Master has sent all binlog to slave; waiting for binlog to be up","Info":"","StartedAt":"2015-11-11 15:02:55"},{"Instance.....}]
```

**Comment by shlomi-noach** [comment]
Aha! `Binlog Dump GTID`. Adding to filters.

**Comment by shlomi-noach** [comment]
pushed, released in https://github.com/outbrain/orchestrator/releases/tag/v1.4.529
