### ISSUE TITLE
Ignoring promotion of slave does not work

### ISSUE THREAD

**Issue by leoleovich** [outbrain/orchestrator#123]
There is my config file:
```
  ...
  "DenyAutoPromotionHostnamePattern": [
    "aw-db[0-9]+(-t)?-[a-z]+-[a-z]+"
  ],
  "PromotionIgnoreHostnameFilters": [
	"aw-db[0-9]+(-t)?-[a-z]+-[a-z]+"
  ],
  "RecoveryIgnoreHostnameFilters": [
	"aw-db[0-9]+(-t)?-[a-z]+-[a-z]+"
  ],
  "RecoverMasterClusterFilters": [
  	"a[fw]-db[0-9]+(-t)?-[a-z]+-[a-z]+"
  ],
  "RecoverIntermediateMasterClusterFilters": [
  	"a[fw]-db[0-9]+(-t)?-[a-z]+-[a-z]+"
  ],
  ...
```
And if I test regex:
```
aw-db01-t-foe-wallet:~# hostname -f | grep -E "aw-db[0-9]+(-t)?-[a-z]+-[a-z]+"
aw-db01-t-foe-wallet
aw-db01-t-foe-wallet:~#
af-db02-t-foe-wallet:~# hostname -f | grep -E "aw-db[0-9]+(-t)?-[a-z]+-[a-z]+"
af-db02-t-foe-wallet:~#
```
But in cluster view I see that aw-db01-t-foe-wallet will be promoted (the star sign).
<img width="821" alt="promotionproblem" src="https://cloud.githubusercontent.com/assets/4749052/11066350/26fb2ebe-87c8-11e5-8f65-d49c68be3b25.png">

Any ideas?:)

**Comment by shlomi-noach** [comment]
The "star" sign doesn't mean the instance will be promoted. It means it is most up to date at this time.
I may actually remove the "star" sign shortly.

However DO NOTICE: in the case of master-master replication it is _expected_ and _assumed_ that the other co-master is the one to be promoted in case of failure. Moreover, orchestrator will consider it a recovery failure should it not succeed in promoting the remaining co-master.

I actually do not agree that you should be using co-master topology if you do not intend the _other_ co-master to be promoted. I'm happy to understand your particular use case.

**Comment by leoleovich** [comment]
Hey.
Thank you for quick answer.
I have 2 DC. In both DCs I have local copy of the application. Each copy writes to own DC.
But traffic goes always to the 1st DC and will be switched to the 2nd only in case of disaster in the 1st one.
That means that I need to make switches only in the first one and I prefer to say which slave I want to use and not by internal logic.

**Comment by leoleovich** [comment]
My point is - it would be very good to have possibility to configure an order of slaves to promote.

**Comment by leoleovich** [comment]
I changed topology of my cluster to make it work. Thanks for your time.

**Comment by shlomi-noach** [comment]
Cross-DC explanation is fair enough, and I'm using similar logic, but not in a master-master replication.
I can support this via configuration flag "CoMasterRecoveryRequireCoMasterPromotion" (defaults `true`, implies current behavior).

FYI, get familiar with "register-candidate" command. This still evolves, but at this time the following is complete and stable:

- When you "register-candidate" an instance, it is marked as "prefer to be promoted".
- You need to re-register it, because this recommendation expires. See `CandidateInstanceExpireMinutes`.
- Upon master failure, orchestrator will make _best effort_ to promote your candidate server. You will at the very least want it to have `log-slave-updates`.

**Comment by shlomi-noach** [comment]
I'm reopening as your original setup is valid and makes sense whether I like it or not, and should be supported.

**Comment by leoleovich** [comment]
Thank you. I am ready to help you with testing.

**Comment by leoleovich** [comment]
But I am not sure if we need to have separate option for it. IMHO would be better to have option for "preferable slave", which will be tried on the first place. Maybe even list of them to have some kind of control...

**Comment by shlomi-noach** [comment]
Please scroll up to learn more about candidate slaves.

I know of use cases where regardless of anything, a co-master failover *must* failover to the other co-master, and this overrides any candidate slaves. So I will keep this particular behavior via configuration.

**Comment by shlomi-noach** [comment]
co-master recovery now behaves as follows:
- when `CoMasterRecoveryMustPromoteOtherCoMaster` is `true` (as is the default) we must promote the co-master or else this is a failure
- when the other co-master is writable, we must promote the co-master or else this is a failure
- when `CoMasterRecoveryMustPromoteOtherCoMaster` is `false` and the other co-master is `read-only`, we will promote whichever slave makes most sense, taking into account candidate slaves.
- however if the other co-master is in same DC and environment as promoted slave, we still prefer putting it on top
- If, eventually, we promoted a slave which is not the other-co-master, we forcibly (and even if `ApplyMySQLPromotionAfterMasterFailover` is `false`) detach is from its original master (we use `detach-slave-master-host`) so as to break the logical 3-way replication circle that is simplied by the promotion.
