### ISSUE TITLE
Orchestrator UI gives 'Unauthorized' error when instance is read_only

### ISSUE THREAD

**Issue by ipodor** [outbrain/orchestrator#134]
When I attempt to make a change in the UI on an instance that's read only, the error message given is 'Unauthorized' even though, no authentication enabled.

It would be nicer to have the options disabled completely or get a read_only warning instead.

**Comment by shlomi-noach** [comment]
It should be trivial to hide the instance modal-dialog's buttons that modify-data or take-action (and right now I believe all of them are).

The drag-n-drop operations should be disabled for read-only orchestrators.

Are there any further actions you have identified for which this should be applied?

**Comment by ipodor** [comment]
Haven't run into anything else. thanks for the follow up :)

**Comment by shlomi-noach** [comment]
Pushed downstream https://github.com/github/orchestrator/pull/12
will soon push upstream

**Comment by shlomi-noach** [comment]
Pushed upstream
