### ISSUE TITLE
False positive failover during backup

### ISSUE THREAD

**Issue by leoleovich** [outbrain/orchestrator#138]
I notice, that in some circumstances you can have a false positive failover.
I have xtrabackup running on second Master in Master-Master topology.
It is stopping slave threads for time of backup. If something happened with 1st Master from point of view orchestrator (network flapping or whatever) it will start failover process.

There is a code listing, which, in my opinion, cost us a problem:

https://github.com/outbrain/orchestrator/blob/552eaa61d78a4ebcfd016a74b55dc3cb3e3108b0/go/inst/analysis_dao.go#L61-L63

And this kinda in conflict with 
https://github.com/outbrain/orchestrator/blob/552eaa61d78a4ebcfd016a74b55dc3cb3e3108b0/go/inst/analysis_dao.go#L55-L57
Where you are, actually, check if slave has an error.

**Comment by shlomi-noach** [comment]
Not all crashes necessarily cause an IO error on the slave; some cause for stall; other cause for no-new-data.
However you'll be happy to learn there's a command integrated for those exact cases, where you initiate a routine that would potentially/certainly cause a failure detection.
When beginning the backup, please invoke "begin-downtime" on the backed up server. When you allow your slaves to run again, issue a "end-downtime" on the backed up server.

A downtimed server will not be failed over.
