### ISSUE TITLE
Hostname patterns without hostnames

### ISSUE THREAD

**Issue by enisoc** [outbrain/orchestrator#150]
I'd like to be able to set up classifications like DataCenter, PhysicalEnvironment, and PromotionIgnore. However, I don't have any control over hostnames in an environment like Kubernetes, where hostnames are assigned as random strings. Actually, those random hostnames are not resolvable from other hosts anyway, so I end up just using IP addresses (which are also random).

Is it possible to set up some way for me to inject a string of my choosing into each mysqld, which doesn't have to be an actual hostname, but will be used for things like determining DataCenter and PromotionIgnore?

**Comment by shlomi-noach** [comment]
Apologies for being slow to respond.
The alternative I see to parsing a hostname is issuing a query (similarly to `SlaveLagQuery` or `DetectClusterAliasQuery`). However, issuing a query on a replica typically ends up with the same info as the master.
An exception to this would be a query of the form `SELECT LOAD_FILE('/path/to/env-hint.txt')` which would require you to grant the `FILE` privilege as well as make sure `apparmor` or what have you allow such queries in the first place.
Makes sense?

**Comment by shlomi-noach** [comment]
Re: `PromotionIgnore`, this will be possible via marking the hosts online. That is, not configuration-based but state based. You will be able to `orchestrator -c register-candidate --promotion-rule=must_not`. Work on this has begun.

**Comment by enisoc** [comment]
The LOAD_FILE option is an interesting idea. It would be useful for environments where every instance has its own isolated file space (which is the case for Kubernetes). What do you think about something like this:

New config option:

`InstanceConfigFile`: Path to a JSON file to look for on each instance (via `SELECT LOAD_FILE()`, requiring `FILE` privilege for the orchestrator user) that allows manually specifying certain instance attributes that otherwise would be inferred by Orchestrator.

For example:

```
# orc-instance.json
{
  "Alias": "vt-0000062348", # just an idea; human-readable name, not used for resolving/connecting
  "ClusterName": "main.shard-23",
  "DataCenter": "dc1",
  "PhysicalEnvironment": "dc1-prod",
  "PromotionRule": "must_not",
}
```

**Comment by shlomi-noach** [comment]
This is potentially a good solution.
I have another idea which is to expect a [`CSV` table](http://dev.mysql.com/doc/refman/5.7/en/csv-storage-engine.html).
Such table would be placed physically on each server, and no statement will ever write to it, and so replication is taken out of the equation. I've played with it before -- it is OK to swap the data live.
Such table could hold a key/value column setup.

**Comment by shlomi-noach** [comment]
```bash
# sudo mysql mysql -e "create table local_metadata (metadata_key varchar(64) charset ascii not null, metadata_value varchar(255) charset ascii not null) engine=csv"
$ echo "Alias,vt-0000062348" >> local_metadata.CSV
$ echo "ClusterName,main.shard-23" >> local_metadata.CSV
$ echo "DataCenter,dc1" >> local_metadata.CSV
$ sudo mysql mysql -e "select * from local_metadata"
+--------------+----------------+
| metadata_key | metadata_value |
+--------------+----------------+
| Alias        | vt-0000062348  |
| ClusterName  | main.shard-23  |
| DataCenter   | dc1            |
+--------------+----------------+
```

**Comment by enisoc** [comment]
That sounds nice too, and it would work for multiple instances on the same file system (in different data dirs). Whoever's setting up those tables (in my case Vitess) would need to blacklist `local_metadata` during backup/restore, or ensure they're always overwritten after restore.

If the goal of writing the CSV file directly is to avoid replication, what about using [replicate-ignore-table](http://dev.mysql.com/doc/refman/5.6/en/replication-options-slave.html#option_mysqld_replicate-ignore-table):

```
--replicate-ignore-table=orchestrator.local_metadata
```

Then I could set the values from within a SQL session.

**Comment by shlomi-noach** [comment]
So I've been thinking, this is not so different than populating a table with `SET session.sql_log_bin=0; REPLACE INTO...`.
Replication filtering are scary.

**Comment by enisoc** [comment]
I'd be ok with wrapping my changes to `local_metadata` in `sql_log_bin=(0|1)` if you're suggesting that's safer than `replicate-ignore-table`. Is the latter known to have issues? I know `(replicate|binlog)-ignore-db` had a dangerous bug before, and even after that the behavior is often not what you'd expect (because it only works with `USE`). But I thought `replicate-ignore-table` was supposed to be the answer to those problems.

**Comment by shlomi-noach** [comment]
You may be right. With replication filtering, especially multiple ones, it becomes difficult to understand whether one MySQL instance represents a true subset of another. At my previous company we had sub-branches with different replication filters. It was then dangerous/forbidden to relocate replicas in between those two branches. Likewise it was invalid to promote any of them. And if local master would break, all hell breaks loose.
If everything is perfectly aligned, then you can sleep well.

Anyway, this turns into an implementation discussion, where on orchestrator's side, this just means it needs to issue a query to get a value, and it's on you to decide how to implement that. Excluding your original JSON query, which needs some logic on orchestrator's side, all the rest merely require that we have a special query config variable per piece of information we're looking for.

**Comment by enisoc** [comment]
That's a good point. I'll retract my JSON idea then, since having a separate query per item seems more flexible.

**Comment by shlomi-noach** [comment]
This was closed because of automated text parsing. What's missing is the `promotion_rule` which will be pushed shortly.
https://github.com/outbrain/orchestrator/pull/161

**Comment by enisoc** [comment]
Is it possible to also have a DetectPromotionRuleQuery? I'd prefer to be able to set that as a persistent value in the mysqld, such that if it gets discovered by orchestrator, it will immediately know it must not promote it.

**Comment by shlomi-noach** [comment]
Yes, this will be supported shortly. The only accepted promotion rules at this time will be:
-  `must_not`
- `neutral`
- `prefer`
I'm uncertain whether I will implement logic for `prefer_not` and `must`.

**Comment by shlomi-noach** [comment]
This was closed by contribution from Vitess
