### ISSUE TITLE
Implement MHA like masterha_master_switch functionality

### ISSUE THREAD

**Issue by djuntgen** [outbrain/orchestrator#151]
# Use Case:

1. Perform maintenance on db1 (master)
2. Promote db2 as master
3. Move reader VIP from `db2 -> db1`

Take the following topology:
```
db1 (Master - Holds app read/write VIP)
\
 +--> db2 (Replica - Candidate for master and holds app reader VIP)
 |
 +--> db3 (Replica - Backup server, holds app backup VIP)
```

In this case we have three VIPs:

1. Master VIP
2. Reader VIP
3. Backup VIP

## Master Switch (Cluster Health - OK)

In this use case all servers are healthy, replication is working and all is ok. Using Orchestrator,perform a master switch between `db1` and `db2`.

- From CLI
  - `orchestrator -c master_switch_alive -i db1 -d db2`
- From UI
  - Drag eligible replica `db2` onto current master `db1`
  - Prompt user to make `db2` `co-master` or `switch-master`
  - *backend does magic, calls `orchestrator -c master_switch_alive -i db1 -d db2`*
- Hooks
  - need before, middle and after hooks that allow for VIP management

## Result

Successful master switch:
```
db2 (Master - Holds app read/write VIP)
\
 +--> db1 (Replica - Candidate for master and holds app reader VIP)
 |
 +--> db3 (Replica - Backup server, holds app backup VIP)
```

See MHA[ `masterha_master_switch --master_state=alive --orig_master_is_new_slave`](https://code.google.com/p/mysql-master-ha/wiki/masterha_master_switch#Scheduled(Online)_Master_Switch)

**Comment by shlomi-noach** [comment]
Will work on this.
Question: as far as I can see, the hooks would be identical to those of a DeadMaster recovery. That is, I'm not going to try and fix the old master or make it connectable to the topology (you may choose to do so yourself via `make-co-master` command).

Also noteworthy we will want a `FLUSH TABLES WITH READ LOCK` since we don't want to lose data in a planned switchover. This may cause further stall.

**Comment by djuntgen** [comment]
@shlomi-noach - Hooks are identical to DeadMaster yes. Only different here is that the current master would automatically be made a replica of the replica that was made master.

You are correct, if you look at MHA's masterha_master_switch it does perform a FTWR.

Thanks!

**Comment by shlomi-noach** [comment]
Please see https://github.com/outbrain/orchestrator/pull/179

**Comment by shlomi-noach** [comment]
See further https://github.com/outbrain/orchestrator/pull/191

**Comment by ManjotS** [comment]
IP Addresses could be managed using orchestrator and orchestrator-agent to do the work.

A database called orchestrator could be created with a vip table. In the table would be key value with the vip name, ie "r" and the value of the ip. If orchestrator config is set to manage vips, it will look for, or create this this table. 

These vips could then show on the interface as well. During failover, they would be added or removed as aliases on the servers. We could make the actual script a hook to orchestrator agent, so other technologies (corosync, keepalived, elb, haproxy) etc could be leveraged.
