### ISSUE TITLE
[Proposal] Support running with semi-sync enforced (async fallback disallowed)

### ISSUE THREAD

**Issue by enisoc** [outbrain/orchestrator#156]
I'm interested in using Orchestrator with rpl_semi_sync_master_wait_no_slave=1 and rpl_semi_sync_master_timeout=huge because I want a totally partitioned master to refuse all writes (to let the other side elect a new master without creating alternate futures).

That means it's important to update rpl_semi_sync_master_enabled when transitioning between master and slave roles. Otherwise leaf slaves will get stuck, since they have no slaves of their own to send ACKs.

I'm looking at contributing a patch for this, but I wanted to open an issue to discuss the proposal first.

**Comment by enisoc** [comment]
@shlomi-noach do you have any thoughts on this proposal before I start working on it? I'm thinking of adding a config setting similar to `RecoverMasterClusterFilters` that specifies which clusters should maintain semi-sync settings for wait_no_slave mode.

**Comment by shlomi-noach** [comment]
@enisoc so if I understand correctly, it's on the ops people to setup the first semi-sync, but orchestrator should notice that, and in the event of master promotion it should apply the semi sync to some designated/random server?

**Comment by enisoc** [comment]
To elaborate, what I'm doing now is that Vitess sets up replication initially, including these `wait_no_slave` semi-sync settings. Vitess will also toggle semi-sync appropriately when you ask Vitess to do failovers for you.

Now what I'm working on is the ability to add Orchestrator to the mix. Orchestrator then needs to do the following on any cluster that matches `SemiSyncWaitNoSlaveClusterFilters`:

1. Before promoting a master, set `rpl_semi_sync_master_enabled=1`. The `rpl_semi_sync_master_wait_no_slave` and `rpl_semi_sync_master_timeout` values will already have been set since startup in the `my.cnf`.
2. Before connecting a promotion-eligible slave to the master, set `rpl_semi_sync_master_enabled=0` and `rpl_semi_sync_slave_enabled=1`. The former must be set to allow the slave to replicate despite having no slaves of its own. The latter must be set before `START SLAVE` so that the slave will send semi-sync ACK. Note that slaves with `PromotionRule=must_not` should instead set `rpl_semi_sync_slave_enabled=0` (so they don't ACK) because we don't want them to be the farthest ahead if the master goes down.

**Comment by shlomi-noach** [comment]
OK, very good.
I'm wondering whether orchestrator should just note that the failed master used to have `rpl_semi_sync_master_enabled=1`, and by default attempt to apply the same on the promoted slave, including setting `rpl_semi_sync_master_enabled=0` and `rpl_semi_sync_slave_enabled=1` on newly attached slaves, as you suggest.
Do you see a reason why this would not make sense as the default behavior _for clusters where the failed master was doing semisync_?

**Comment by enisoc** [comment]
I worry that relying on observing the value of `rpl_semi_sync_master_enabled` on the previous master could be subject to race conditions, as that value can change at runtime (if the user requests Vitess to do a failover, for example). If the chain of observations is ever broken (it happens to observe 0), Orchestrator could forget that this cluster had `rpl_semi_sync_master_enabled=1`. The purpose of running in this mode is to strengthen the guarantees against data loss during DeadMasterRecovery, and that break in the chain would defeat this protection. That's why my proposal is a top-down decree rather than a bottom-up inference.

**Comment by shlomi-noach** [comment]
OK. We can go with `SemiSyncWaitNoSlaveClusterFilters` config definition. I'm curious what the `NoSlave` substring of `SemiSyncWaitNoSlaveClusterFilters` means.
Would `EnforceSemiSyncClusterFilters` be a good naming choice?

**Comment by enisoc** [comment]
I agree my suggested name is awkward. I chose `*WaitNoSlave` to correspond with `rpl_semi_sync_master_wait_no_slave`, whose implication is "the master will wait for an ACK, even if it has no slaves connected".

The default behavior is to not bother waiting if it knows there's no one there to answer. So it isn't usually necessary to toggle `rpl_semi_sync_master_enabled` in the manner we're discussing, unless you're running with `wait_no_slave=1`. I thought people who are used to running semi-sync in default mode would be surprised that a setting named simply `EnforceSemiSync*` would cause this toggling.

Maybe something like `ToggleSemiSyncClusterFilters`? This makes it clear that the purpose is to cause toggling. If they want to know why you'd want such toggling, we'll explain that in the manual.

**Comment by shlomi-noach** [comment]
Pushing this naming discussion a little further, it's fine to go with `NoSlave` since it relates to `rpl_semi_sync_master_wait_no_slave`. Let's just hint that this relates to master failover in the form of: `MasterFailoverSemiSyncWaitNoSlaveClusterFilters` ?
And please feel free to pursue this. Names can be changed during PR :)

**Comment by enisoc** [comment]
After digging in the code more, I'm backtracking on making this a cluster-wide `*ClusterFilter` option. I want to enforce semi-sync toggling at the level of something like `inst.StartSlave()`. If we make it a cluster-wide setting, `inst.StartSlave()` would need access to the `ClusterInfo` object to decide what to do, which doesn't seem right.

As an alternative, what if we add `SemiSyncEnforced bool` on `Instance`, and add a config option `DetectSemiSyncEnforcedQuery`. The implication is that "SemiSyncEnforced" means "semi-sync is enforced on this instance - that is, the instance is not allowed to fall back to async for any reason, be it a timeout or a lack of slaves".

The user could either make this query check its instance-local config table (like we've discussed in #150), or could use something like this:

```
SELECT @@global.rpl_semi_sync_master_wait_no_slave AND @@global.rpl_semi_sync_master_timeout > 1000000
```

Unfortunately there's no value of `rpl_semi_sync_master_timeout` that means "infinite" so we have to set some finite threshold, which is another good reason to let the user customize this query.

Let me know if you have any thoughts on this. I'll keep looking into it.

**Comment by shlomi-noach** [comment]
I'm wondering whether per-server semi-sync flagging would not throw you down a rabbit hole. You'd need to tediously configure your servers, and then reconfigure them upon promotion. Is that the case?

**Comment by enisoc** [comment]
I'm not sure what you think would make it tedious, but let me try to clarify what I'm thinking. All servers in the cluster should have the same semi-sync settings in my.cnf:

```
plugin-load = rpl_semi_sync_master=semisync_master.so;rpl_semi_sync_slave=semisync_slave.so
rpl_semi_sync_master_timeout = 1000000000000000000
rpl_semi_sync_master_wait_no_slave = 1
```

Note that the config does not enable semi-sync anywhere at startup. Then it is up to Orchestrator (and/or Vitess) to enable/disable semi-sync as appropriate. The operator shouldn't need to reconfigure anything by hand.

**Comment by enisoc** [comment]
#187 fixes this.
