### ISSUE TITLE
read credentials from mysql.slave_master_info

### ISSUE THREAD

**Issue by shlomi-noach** [outbrain/orchestrator#163]
when `master_info_repository = TABLE` orchestrator (given privileges) could read credentials from `mysql.slave_master_info`. This can enable it to `CHANGE MASTER TO` on a credentials-less master, doing planned switchovers.

- orchestrator should not store such credentials. 
- add a column `replication_credentials_available BOOL` to indicate that such credentials are in fact accessible upon request

**Comment by grypyrg** [comment]
You can also read credentials when `master_info_repository = FILE`:

```
mysql> SELECT IF(@@global.secure_file_priv = NULL, 'FAIL', 'OK');
+----------------------------------------------------+
| IF(@@global.secure_file_priv = NULL, 'FAIL', 'OK') |
+----------------------------------------------------+
| OK                                                 |
+----------------------------------------------------+
1 row in set (0.00 sec)

mysql> CREATE TEMPORARY TABLE test.replication_credentials (txt VARCHAR(255));
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT CONCAT(@@global.datadir, "/master.info");
+------------------------------------------+
| CONCAT(@@global.datadir, "/master.info") |
+------------------------------------------+
| /var/lib/mysql//master.info              |
+------------------------------------------+
1 row in set (0.00 sec)

mysql> LOAD DATA INFILE '/var/lib/mysql//master.info' INTO TABLE test.replication_credentials;
Query OK, 23 rows affected (0.00 sec)
Records: 23  Deleted: 0  Skipped: 0  Warnings: 0

mysql> SELECT txt FROM test.replication_credentials LIMIT 4,2;
+--------------+
| txt          |
+--------------+
| repl         |
| vagrant_repl |
+--------------+
2 rows in set (0.00 sec)

mysql> DROP TABLE test.replication_credentials;
Query OK, 0 rows affected (0.00 sec)
```

Dirty isn't it :smile_cat:

**Comment by shlomi-noach** [comment]
Very nice!
I tried LOAD_FILE but that did not work. Will LOAD DATA INFILE work where
LOAD_FILE would not?

Isn't there a difference in the Number of rows between versions? In between
5.5 and 5.6 or 5.6 and 5.7? I seem to remember something.

**Comment by grypyrg** [comment]
- Yes, different mysql versions have different number of rows. IMO the username and password rows remain the same (could be wrong on this)
- trying `LOAD_FILE`:

```
mysql> SELECT IF(@@global.secure_file_priv = NULL, 'FAIL', 'OK');
+----------------------------------------------------+
| IF(@@global.secure_file_priv = NULL, 'FAIL', 'OK') |
+----------------------------------------------------+
| OK                                                 |
+----------------------------------------------------+
1 row in set (0.01 sec)

mysql> CREATE TEMPORARY TABLE test.replication_credentials (txt VARCHAR(255));
Query OK, 0 rows affected (0.11 sec)

mysql> SELECT CONCAT(@@global.datadir, "/master.info");
+------------------------------------------+
| CONCAT(@@global.datadir, "/master.info") |
+------------------------------------------+
| /var/lib/mysql//master.info              |
+------------------------------------------+
1 row in set (0.00 sec)

mysql> LOAD DATA INFILE '/var/lib/mysql//master.info' INTO TABLE test.replication_credentials;
Query OK, 23 rows affected (0.06 sec)
Records: 23  Deleted: 0  Skipped: 0  Warnings: 0

mysql> SELECT txt FROM test.replication_credentials LIMIT 4,2;
+--------------+
| txt          |
+--------------+
| repl         |
| vagrant_repl |
+--------------+
2 rows in set (0.00 sec)

mysql> SELECT LOAD_FILE('/var/lib/mysql//master.info');
+------------------------------------------+
| LOAD_FILE('/var/lib/mysql//master.info') |
+------------------------------------------+
| NULL                                     |
+------------------------------------------+
1 row in set (0.00 sec)
```

You're right. `LOAD_FILE` for some reason does not work, but `LOAD DATA INFILE` does.

**Comment by shlomi-noach** [comment]
Oh cool! Thanks for the workaround!

**Comment by grypyrg** [comment]
It would be great if you implement this and then recommend in the manual to run mysql in 'insecure mode' :smiling_imp:

**Comment by shlomi-noach** [comment]
Your initial check was invalid:

> `SELECT IF(@@global.secure_file_priv = NULL, 'FAIL', 'OK');`

should be:

> `SELECT IF(@@global.secure_file_priv IS NULL, 'FAIL', 'OK');`

**Comment by shlomi-noach** [comment]
Or, rather, it should be the other way around!

`SELECT IF(@@global.secure_file_priv IS NULL, 'OK', 'FILE');`

**Comment by shlomi-noach** [comment]
Further issues:
- Need `CREATE TEMPORARY TABLES` grant. 
- Need a schema for the above (`information_schema` will not work)
- Need `SELECT, INSERT, DELETE` grants on the table; these cannot be granted because the table does not exist. So must have those grants _schema-wide!_
- Which is bad for security

**Comment by grypyrg** [comment]
If only it would work with `LOAD_FILE()`, then all the issues would be resolved. Why does it not work actually?

**Comment by grypyrg** [comment]
Strange, it seems like `LOAD_FILE()` is protected from reading the `master.info` file, I can read another me file with the same contents properly.

**Comment by shlomi-noach** [comment]
I'm not going to proceed with the `master.info` hack; there's just too much configuration involved that makes this an unappealing approach for orchestrator.

**Comment by grypyrg** [comment]
I originally meant it as a joke even @shlomi-noach :). Also, did you implement reading credentials from `TABLE`? (as this issue is closed)

**Comment by shlomi-noach** [comment]
Credentials from TABLE is implemented. See also
https://github.com/outbrain/orchestrator/issues/81
