### ISSUE TITLE
Wiki https://github.com/outbrain/orchestrator/wiki/Orchestrator-for-developers doesn't provide the correct instructions with the new 1.5 vendoring

### ISSUE THREAD

**Issue by sjmudd** [outbrain/orchestrator#165]
The build as described in the wiki does not work.
If you use ./build.sh then this does work fine as you use the vendored packages, so probably the documentation needs to be updated here to mention vendoring and to say use ./build.sh to build rather than using go build directly. (or if not to set GO15VENDOREXPERIMENT=1 first).

So the current setup while your vendored branch on go-cache uses the old repo won't build without this setting.

**Comment by shlomi-noach** [comment]
Fixed in https://github.com/outbrain/orchestrator/wiki/Orchestrator-for-developers
