### ISSUE TITLE
Orchestrator active node re-election takes place during DST switch

### ISSUE THREAD

**Issue by sjmudd** [outbrain/orchestrator#190]
Hi,

I noticed that on switching to daylight savings time (CET to CEST, 2am --> 3am) the orchestrator active node election kicked in and changed the active node in an orchestrator cluster setup I have.

I have an additional patch which notifies me of this situation and the timing happened at exactly 3am local time (that is just after the switch).  While the change in active master was not a big problem perhaps it's worth doing something to prevent this, probably by treating the times used in the active node election in UTC rather than local time.

**Comment by shlomi-noach** [comment]
This makes sense. The check for failed nodes is based on last written timestamp, and that suspiciously turns to be 1-hour old all of a sudden.
My immediate recommendation is to modify your orchestrator's backend MySQL to use UTC. I'm not sure orchestrator should explicitly use UTC for node-election as opposed to other operations. Doing so would mean it would be harder to compare and analyze histories.

**Comment by dveeden** [comment]
Maybe orchestrator should use SET SESSION time_zone=UTC?

**Comment by shlomi-noach** [comment]
@dveeden this is possible, but would need to be coordinated on all your orchestrator deployments
- This is not a big problem in itself, but if we're going to introduce such behavior, it will be flagged by a configuration variable, which means you will need to distribute said variable on all your deployments
- and other clients will not use same `time_zone`. Is the `heartbeat` event using this `time_zone`? The `pseudo-gtid` event? (however you use them)

The correct solution still seems to me to set up your mysql servrs to `UTC`, or otherwise set `init-connect=...`

**Comment by sjmudd** [comment]
Hi Shlomi,

Thanks for your response. I agree that a server setup to use UTC does make the problem go away.  That is indeed a good setup to use, but I wonder if everyone will have their systems configured that way, or if they can adjust their existing setup as needed.
Note: timestamps are actually stored in UTC (internally), since the unix epoch so possibly all that is needed is to convert the localtimes to UTC when doing the various calculations related to leader election.  Given the number of queries involved here the queries may look a bit more cumbersome but that should work fine. That said Daniel noticed https://bugs.mysql.com/bug.php?id=80863 meaning that if you do any conversions probably you only want to compare UNIX_TIMESTAMP(<column>) values and that should be safe whatever timezone the server uses.

**Comment by shlomi-noach** [comment]
OK, we have 6 months to think this over. Right now this is not a priority -- nor is there actual damage in the leader change. Any pending recovery keeps on executing. New recoveries will be picked by the new leader.

**Comment by sjmudd** [comment]
Indeed. This was just a heads up.

**Comment by shlomi-noach** [comment]
I'm closing this as I don't consider this to be a bug.
