### ISSUE TITLE
cluster_name` should be `varchar(128) NOT NULL`

### ISSUE THREAD

**Issue by shlomi-noach** [outbrain/orchestrator#195]
It is wrongly `TINYTEXT` which causes for query suboptimization

**Comment by sjmudd** [comment]
The following change helps me at least:
Applying: `alter table database_instance modify cluster_name varchar(128) not null;`

Changing output from:
`XXX rows in set (0.13 sec)`
to:
`XXX rows in set (0.01 sec)`

**Comment by shlomi-noach** [comment]
Fixed downstream; will merge changes shortly.
