### ISSUE TITLE
relocate command doesn't relocate the slave

### ISSUE THREAD

**Issue by AshokJivani** [outbrain/orchestrator#205]
Setup:

3 servers: myserver1, myserver2 and myserver3
1. myserver1 is master and others are slave
2. stopping MySQL on myserver1 and let orchestrator promote one of the slave (in my case myserver3)
3. starting MySQL on myserver1 and tried to relocate under myserver3 (current master)

Issue:
Even though the relocate command runs successfully, it actually doesn't relocated myserver1 under myserver3.

`[root@orchadmin ~]# orchestrator -c relocate -i myserver1 -d myserver3`
`2016-04-29 11:55:27 DEBUG Hostname unresolved yet: myserver1`
`2016-04-29 11:55:27 DEBUG Cache hostname resolve myserver1 as myserver1`
`2016-04-29 11:55:27 DEBUG Hostname unresolved yet: myserver3`
`2016-04-29 11:55:27 DEBUG Cache hostname resolve myserver3 as myserver3`
`2016-04-29 11:55:27 DEBUG Initializing orchestrator`
`2016-04-29 11:55:29 DEBUG auditType:relocate-below instance:myserver1:3306` `cluster:myserver1:3306 message:relocated myserver1:3306 below myserver1:3306`
`myserver1:3306<myserver3:3306`

`[root@orchadmin ~]# orchestrator -c topology -i myserver1` 
`2016-04-29 12:03:23 DEBUG Hostname unresolved yet: myserver1`
`2016-04-29 12:03:23 DEBUG Cache hostname resolve myserver1 as myserver1`
`2016-04-29 12:03:23 DEBUG Initializing orchestrator`
`2016-04-29 12:03:23 DEBUG instanceKey: myserver1:3306`
`myserver1:3306 [0s,ok,5.6.28-76.1-56-log,ro,ROW,>>]`

`[root@orchadmin ~]# orchestrator -c topology -i myserver3`
`2016-04-29 12:03:27 DEBUG Hostname unresolved yet: myserver3`
`2016-04-29 12:03:27 DEBUG Cache hostname resolve myserver3 as myserver3`
`2016-04-29 12:03:27 DEBUG Initializing orchestrator`
`2016-04-29 12:03:27 DEBUG instanceKey: myserver1:3306`
`2016-04-29 12:03:27 DEBUG instanceKey: myserver2:3306`
`2016-04-29 12:03:27 DEBUG instanceKey: myserver2:3306`
`2016-04-29 12:03:27 DEBUG instanceKey: myserver3:3306`
`2016-04-29 12:03:27 DEBUG instanceKey: myserver3:3306`
`myserver3:3306 [0s,ok,5.6.28-76.1-56-log,rw,ROW,>>]`
`+ myserver2:3306 [0s,ok,5.6.28-76.1-56-log,ro,ROW,>>,GTID]`

**Comment by shlomi-noach** [comment]
@AshokJivani apologies for the late reply; ironically I had notifications misconfigured.

This has been fixed in a recent version; can you check out the latest release? https://github.com/outbrain/orchestrator/releases

**Comment by shlomi-noach** [comment]
@AshokJivani can you please confirm? I'd like to close this

**Comment by AshokJivani** [comment]
@shlomi-noach with v1.5.0, It works as expected. Thanks for following up on this.

**Comment by shlomi-noach** [comment]
Perfect, thank you!
