### ISSUE TITLE
Instruct orchestrator to apply all binlogs slave(s) already received before promotion

### ISSUE THREAD

**Issue by AshokJivani** [outbrain/orchestrator#207]
I have tested orchestrator where a master gets writes (loop of pk inserts on a table) and both slaves have stopped SQL threads but keeping IO thread running. After 1hr or so:
1. Start SQL threads on both slaves 
2. Stop MySQL on master. 
3. Orchestrator performs failover (choosing the one slave which is ahead as a new master).
4. Start MySQL on old master and compare records on old master/new master. 

Even though both slaves have received all IO events from the master, it doesn't apply all before promotion. (the record count on old master is significantly higher then new master)

Is there a way to instruct orchestrator to wait until all slaves apply all binlog events it already received before perform failover? I feel like preFailover script is a way to go but just checking if there is any other configuration parameter which forces such behavior.

Really appreciate any suggestions.

**Comment by shlomi-noach** [comment]
Apologies for this late response; ironically I had my notifications misconfigured.

I understand your case; however the purpose of orchestrator is to fail over as quickly as possible. Currently there is no such configuration variable, though I suppose one can be produced. 

The notion of failing over by waiting for some 10 minutes for all replicas to catch up is not very appealing, I must say.

**Comment by AshokJivani** [comment]
Shlomi,

Thanks for developing such a great tool to manage replication topology. Really appreciate your work.
 
As per the purpose of Orchestrator, You are right. It should perform failover as quickly as possible. I just wanted to cover an edge case where may be due to a big transaction, all slaves are lagging and orchestrator has to failover. Here is a preFailover script I came up with. The script will keep checking if at least one of the master candidate has applied all binary logs it received, the script will exit and let Orchestrator perform the master promotion.

```
#!/bin/bash
ORC_CONFIG_FILE=/etc/orchestrator.conf.json
USER=`cat $ORC_CONFIG_FILE |grep "MySQLTopologyUser" | cut -d ':' -f2 | sed -e 's/[ ",]//g'`
PASSWD=`cat $ORC_CONFIG_FILE |grep "MySQLTopologyPassword" | cut -d ':' -f2 | sed -e 's/[ ",]//g'`
MY_AUTH="mysql -u$USER -p$PASSWD"
SLAVE_LIST=/tmp/slavelist.$$

# Fetch list of slaves of a DeadMaster but excluding the list which shouldn't promoted at masters from the config file.
EXCLUDE_HOSTS=`awk '/],/ {f=0;next} {$f=$f};f; /PromotionIgnoreHostnameFilters/ {f=1}' $ORC_CONFIG_FILE | sed 's/[",]//g' | xargs | sed -e 's/ /\\|/g'`

/usr/bin/orchestrator -c which-slaves -i $1 --quiet |grep -v -E "${EXCLUDE_HOSTS}" > $SLAVE_LIST

while true; do
    while read slave; do
        S_HOSTNAME=`echo $slave |cut -d":" -f1`
        S_PORT=`echo $slave |cut -d":" -f2`
  
        # Check if given Slave has applied all IO events it received
        POS=$($MY_AUTH -h$S_HOSTNAME -P$S_PORT -e "show slave status\G" | grep "Read_Master_Log_Pos\|Exec_Master_Log_Pos" | cut -d":" -f2 | uniq | wc -l)
        if [[ $POS -eq 1 ]] 
        then
            echo `date "+%Y-%m-%d_%H:%M:%S"` " - $S_HOSTNAME:$S_PORT seems to be in sync. Exiting..." 
            rm -f $SLAVE_LIST
            exit
        else
            echo `date "+%Y-%m-%d_%H:%M:%S"` " - $S_HOSTNAME:$S_PORT is lagging"
        fi
    done < $SLAVE_LIST
    sleep 1
done
```
