### ISSUE TITLE
1.5.0: Web GUI -> Home -> Outdated links

### ISSUE THREAD

**Issue by Co0olCat** [outbrain/orchestrator#219]
Great work. Thank you.

Manual is outdated
FAQ is outdated

As for version 1.5.0

Thank you.

Kind regards,
TY

**Comment by shlomi-noach** [comment]
Apologies for this late response; I've had misconfigured notifications.

Thank you! You are right; I began refactoring documentation and broke some links along the way. Will pursue this.

**Comment by Co0olCat** [comment]
NP. 

Thank you.

Kind regards,
TY
