### ISSUE TITLE
Add Email notifications with secure email config

### ISSUE THREAD

**Issue by Co0olCat** [outbrain/orchestrator#220]
Great work.

It would be nice to add email notifications on major events.

In modern world secure email config should be default.

Thank you.

Kind regards,
TY

**Comment by shlomi-noach** [comment]
Please define "major events" and the type of information you'd like to get.

**Comment by Co0olCat** [comment]
Hi,

Most importantly - when Orchestrator cannot solve issue/heal - inform interested party about issue.
As for the rest -> depending on user selected level: Info, warning, errors.

It is nice to have as well daily/weekly updates -> cluster is up and running, some stats re issues.

Thank you.

Kind regards,
TY

**Comment by shlomi-noach** [comment]
Sorry to nitpick about this, but I really need a clearer definition for this feature request.

> cannot solve issue/heal

All things recovery, you have pre/post hooks, which is what we use for doing whatever you want to do, including mails.

"solve issue" is something I'm unsure what you mean by.

> As for the rest -> depending on user selected level: Info, warning, errors.

I'm tempted to think you might prefer tailing the error log and deciding what to do with the information. For `orchestrator` to send an email for each error/warning -- is a _Very_ noisy operation.

daily/weekly updates: again, need clearer definition.

**Comment by Co0olCat** [comment]
Thank you for your patience.

Can we start with something simple?::

Orchestrator is running as a service -> when issue preventing replication is detected -> send a message.

As for daily/weekly -> this is to keep a tap on how the infrastructure is doing. If there are no daily reports -> maybe service is down or host.

As for mail in general -> I cannot stress more -> it has to be secure.

Thank you.

Kind regards,
TY

**Comment by shlomi-noach** [comment]
> Orchestrator is running as a service -> when issue preventing replication is detected -> send a message.

Please define "issue preventing replication". Do you mean a MySQL problem with replication, such that it breaks replication? Something that has nothing to do with failover/recovery?

The quick and easy answer for that is: orchestrator will not do this. It is not a general-purpose MySQL monitoring solution and will not be. It observes replication and manages failovers, and can at most notify you about failure/recoveries.

> As for daily/weekly -> this is to keep a tap on how the infrastructure is doing. If there are no daily reports -> maybe service is down or host.

Please define "reports". "service is down or host" is strictly not orchestrator's job to alert on. You should use real monitoring/alerting for that.

**Comment by Co0olCat** [comment]
Understood.

Thank you.

Kind regards,
TY
