### ISSUE TITLE
web interface listen on unix socket

### ISSUE THREAD

**Issue by ofbeaton** [outbrain/orchestrator#222]
I'm using a nginx reverse-proxy, and I would like to have orchestrator listen on a unix socket instead of a port.

I don't know Go, but from searching the codebase for the configuration key `ListenAddress` I found it here: https://github.com/outbrain/orchestrator/blob/master/go/app/http.go line 140

That led me to net/http for go, https://golang.org/pkg/net/http/ which I still can't tell if it can take a unix socket instead.

I was expecting something like the nodejs express http server which can take a port or unix socket path.

I tried just providing a socket path like you do in nodejs express
```
"ListenAddress": "/opt/telephony/orchestrator.sock",
```

but the socket failed to create and I got the following in the log files:
```
2016-07-09 03:28:35 INFO Starting HTTP listener
2016-07-09 03:28:35 FATAL listen tcp: missing port in address /opt/telephony/orchestrator.sock
```

If it is indeed possible, what is the syntax to be used? Could the documentation be updated?

If not, could this feature please be added? unix sockets have much less tendency to collide and are much easier to configure when using a reverse proxy on the same box. That way I don't have to worry about the different web services trying to grab the same port.

**Comment by shlomi-noach** [comment]
Apologies for this late response; I had misconfigrued notifications.

Hmmm... I don't know if this is possible, to serve `http` on a unix socket in go. I can look into it.

Having said that, serving `http` on a unix socket is far from being the common practice, so I'm not sure I'd want `orchestrator` to do that. That is, I wouldn't want orchestrator to support a niche feature that is the result of a particular setup.

I've used `nginx` as reverse-proxy myself in the past and did so on TCP ; what is your reasoning for doing so on unix socket?

**Comment by ofbeaton** [comment]
The common configuration for `php-fpm` behind a reverse-proxy used to be http ports as well, and more and more I see both out of the box (php-fpm rpms) and guides switching to unix sockets. e.g. https://support.rackspace.com/how-to/install-nginx-and-php-fpm-running-on-unix-file-sockets/

This is how we run our set up where I work, and how I run things personally as well.

The primary advantage I can see is if for example I have orchestrator, php-fpm, a few node applications... every single one of these apps potentially uses a http port behind my reverse proxy. If say my php-fpm is configured to use port 3000, and I try to install orchestrator, I will have a port conflict and have to start troubleshooting and figure out which of my apps is using this port.

To assume orchestrator will be the only app to ever use port 3000 and port 3001 would be naive. I know they are configurable in each app, but you are just opening yourself up to troubleshooting down the road. However `/var/lib/orchestrator/orchestrator.sock` will never conflict with a different application.

It does, like most things, come with it's own set of drawbacks when scaling it up. e.g. https://easyengine.io/tutorials/php/fpm-sysctl-tweaking/

Pros
- no port conflicts no matter how many apps I install
Cons
- tweaking vars when I scale
- nginx reverse-proxy and app must reside on same box

I wouldn't say this is a niche configuration, it can co-exist with http port apps, but I also would say http port has been the traditional way for a long time. 

I use nodejs express which takes a unix socket just as easily as a port, and php-fpm which also handles both.

**Comment by shlomi-noach** [comment]
Meanwhile it seems listening on a unix socket should not be a problem. I'll put this in the queue

**Comment by ofbeaton** [comment]
Thank you for the quick change!
