### ISSUE TITLE
Question: Rigid structure

### ISSUE THREAD

**Issue by Co0olCat** [outbrain/orchestrator#223]
Hi,

I would like to use Orchestrator, but in our environment we are using stunnel between instances (they are geo separated).

When Orchestrator explorers typology -> it reads settings, say 127.0.0.1:3301, and applies them literally -> on host running orchestrator trying to connect to 127.0.0.1:3301.

I would expect something like below for "manual/rigid" mode:
## |            Master            |           Slave
01 |  alpha@Host01:Port  | beta@Host02:Port
02 |  beta@Host02:Port    | alpha@Host01:Port
03 |  beta@Host02:Port    | gamma@Host03:Port

Here there are three DB hosting servers: alpha, beta and gamma.
Alpha and beta are co-masters. Gamma is slave for alpha.

I would greatly appreciate it if you can advise settings for my setup.

Thank you.

Kind regards,
TY

**Comment by shlomi-noach** [comment]
The problem should be solved if you setup your `report_host` and `report_port` for all your replicas, and make sure your configure orchestrator with `"DiscoverByShowSlaveHosts": true`

**Comment by Co0olCat** [comment]
Thank you.

I was sure the functionality is there. Silly me.

Thank you.

Kind regards,
TY
