### ISSUE TITLE
cluster alias link broken

### ISSUE THREAD

**Issue by ofbeaton** [outbrain/orchestrator#227]
using orchestrator 1.5.0 web app
on the clusters dashboard

each cluster has two links, one that for example says:
`mymaster.mynetwork.blah` and points to `http://mywebsite:3000/web/cluster/alias/mymaster.mynetwork.blah%3A3306`

and right bellow it, another that says:
`mymaster` and points to `http://mywebsite:3000/web/cluster/alias/mymaster.mynetwork.blah:3306`

strangely the one where the `:` is escaped does not work, I get a json error 

```
{
Code: "ERROR",
Message: "No cluster found for alias mymaster.mynetwork.blah:3306",
Details: null
}
```

which is confusing given the 2nd link works.

**Comment by shlomi-noach** [comment]
@ofbeaton on which browser this happens? Does the same problem happen on other browsers?

**Comment by shlomi-noach** [comment]
This is fixed downstream and will be merged soon.

**Comment by ofbeaton** [comment]
It was happening on the latest version of Chrome. I didn't test in IE11.

**Comment by dagmon2** [comment]
Hi,

i have just installed the new orchestrator, version 2.1.1
and i have this exact error.
both on chrome and safari.

working at outbrain btw :)

**Comment by dagmon2** [comment]
Removing cluster aliases from the config file fixed the links for us.

**Comment by shlomi-noach** [comment]
Thank you for updating.

**Comment by shlomi-noach** [comment]
From internal discussions I understand the problem still persists. Can you please clarify again how you set your cluster alias? Please paste your cluster-alias configuration. Thanks!

**Comment by dagmon2** [comment]
Hi,

sure, i'm really sorry for the delayed response,
heres how we configure the cluster aliases in the configuration file

{
  "Debug": true,
  "ListenAddress": ":***",
  "MySQLTopologyUser": "***",
  "MySQLTopologyPassword": "****",
  "MySQLOrchestratorHost": "***",
  "MySQLOrchestratorPort": ***,
  "MySQLOrchestratorDatabase": "***",
  "MySQLOrchestratorUser": "****",
  "MySQLOrchestratorPassword": "****",
  "AgentsServerPort": ":***",
  "ServeAgentsHttp": true,
  "MySQLConnectTimeoutSeconds": 5,
  "AgentsUseSSL": false,
  "SSLSkipVerify": true,
  "SSLCertFile": "/etc/ssl/orchestrator-self-cert.pem",
  "SSLPrivateKeyFile": "/etc/ssl/orchestrator-private-key.pem",
  "UnseenAgentForgetHours": 6,
  "StaleSeedFailMinutes": 60,
  "SeedAcceptableBytesDiff": 8192,
  "PseudoGTIDPattern": "CREATE OR REPLACE .*? VIEW `pseudo_gtid_v` AS
select",
  "SlaveLagQuery": "select lave_lag_seconds",
  "DiscoverByShowSlaveHosts": false,
  "AuditLogFile": "logs/orchestrator-audit.log",
  "AuditPageSize": 20,
  "SlaveStartPostWaitMilliseconds": 1000,
  "InstancePollSeconds": 60,
  "UnseenInstanceForgetHours": 240,
  "AuthenticationMethod": "proxy",
  "AuthUserHeader": "X-Forwarded-User",
  "HTTPAuthUser": "**",
  "HTTPAuthPassword": "****",
  "PowerAuthUsers": [
    "admin"
  ],
  "ClusterNameToAlias": {
    "teamdb9": "Team 9",
    "didb-1": "didb NY",
    "didb-2": "didb LA",
    "didb-4": "didb CHI",
    "dm-": "Database Infrastructure",
    "dbi-": "Database Infrastructure",
    "dwh-": "DWH",
    "jitdb": "Jit DB",
    "mogdb": "Mogile DB",
    "myxtra-": "myxtra",
    "grafanadb": "Grafana DB",
    "wordpressdb": "WordPress DB",
    "cdhdb-1": "cdhdb NY",
    "cdhdb-4": "cdhdb CHI",
    "gludb": "Glu DB",
    "teamdb-4": "Team CHI",
    "team-1": "Team NY",
    "usagestatsdb": "UsageStats DB",
    "wikidb": "Wiki DB",
    "maprdb1": "Maprdb NY",
    "maprdb4": "Maprdb CHI",
    "bidb": "BIDB"
  }

Thanks!
Daniel

**Comment by shlomi-noach** [comment]
https://github.com/github/orchestrator/pull/250 will fix this issue once merged.

**Comment by dagmon2** [comment]
Very cool!

Thanks a lot,

We will upgrade in the following weeks and let you know how it went.

Daniel.
