### ISSUE TITLE
Enable slave skip to skip GTID queries

### ISSUE THREAD

**Issue by ManjotS** [outbrain/orchestrator#251]
Skip slave button with GTID tell us to inject an empty transaction. Do it for us when we click the button.

**Comment by shlomi-noach** [comment]
Which version are you working with? See:

- https://github.com/outbrain/orchestrator/blob/master/resources/public/js/orchestrator.js#L347-L353
- https://github.com/outbrain/orchestrator/blob/master/go/inst/instance_topology_dao.go#L690

**Comment by ManjotS** [comment]
Seems to be solved after updating.
