### ISSUE TITLE
Unhandled UnreachableMasterWithStaleSlaves

### ISSUE THREAD

**Issue by VoroOnestic** [outbrain/orchestrator#259]
Currently, the event UnreachableMasterWithStaleSlaves gets sent to the checkAndRecoverGenericProblem, which does nothing.

In our setup, we need to react to that event, but we also understand that our recovery strategy may not work for everybody. So we have patched topology_recovery.go in order to execute an external process which does the recovery, calling the orchestrator api when needed.
Please look at: https://github.com/VoroOnestic/orchestrator/commit/0889f75a532f88929eae8461af4bfeb064830e66

What do you think of this solution? Should I PR?

**Comment by shlomi-noach** [comment]
Thank you -- looks legit! Please PR

**Comment by VoroOnestic** [comment]
PR merged.
Thanks.
