### ISSUE TITLE
[1.0.3] Last Check Invalid, no such host

### ISSUE THREAD

**Issue by gwinans** [outbrain/orchestrator#26]
Ran 1.0.3 with --stack --debug, here's the output:

[martini] Started GET /api/discover/istsbdcs01-pub.isllc.local/3306
[martini] Completed 200 OK in 3.764292ms
2014-06-30 17:04:46 INFO Starting discovery at {Hostname:istsbdcs01-pub.isllc.local Port:3306}
2014-06-30 17:04:46 INFO No entry for &{Hostname:istsbdcs01-pub.isllc.local Port:3306}
2014-06-30 17:04:46 ERROR lookup : no such host
/home/snoach/dev/outbrain/github/orchestrator/src/github.com/outbrain/log/log.go:105 (0x42cec1)
/home/snoach/dev/outbrain/github/orchestrator/src/github.com/outbrain/log/log.go:151 (0x42d31a)
/home/snoach/dev/outbrain/github/orchestrator/src/github.com/outbrain/orchestrator/inst/instance_dao.go:154 (0x474dad)
/home/snoach/dev/outbrain/github/orchestrator/src/github.com/outbrain/orchestrator/logic/orchestrator.go:76 (0x4806ff)
/home/snoach/dev/outbrain/github/orchestrator/src/github.com/outbrain/orchestrator/logic/orchestrator.go:53 (0x480ed8)
/usr/local/go/src/pkg/runtime/proc.c:1394 (0x4177e0)

=====

Here's the verification of DNS resolution:

[sbduser@istmysqlgw01 orchestrator]$ nslookup istsbdcs01-pub
Server:         10.1.104.30
Address:        10.1.104.30#53

Name:   istsbdcs01-pub.isllc.local
Address: 10.11.1.80

[sbduser@istmysqlgw01 orchestrator]$ nslookup istsbdcs01-pub.isllc.local
Server:         10.1.104.30
Address:        10.1.104.30#53

Name:   istsbdcs01-pub.isllc.local
Address: 10.11.1.80

=====

It appears it can pull information on the mysql instance -- something it hasn't failed to do  -- but something else is failing/causing it to throw the "last check invalid" error.

![host_info](https://cloud.githubusercontent.com/assets/95692/3432847/664d759a-0079-11e4-9a1c-fe93f5a55044.png)

**Comment by shlomi-noach** [comment]
closing this due to long time passed; also so much has been developed in and around this. If you are still affected, please try latest version.
