### ISSUE TITLE
Topology discovery failing for MariaDB 10.1

### ISSUE THREAD

**Issue by rgallast** [outbrain/orchestrator#262]
I'm using orchestrator against MariaDB 10.1 servers and it seems to be having issues when it tries to get the host names of slaves since it would appear that it's trying to access the mysql.slave_master_info table? Log file has:

ERROR ReadTopologyInstance(server1:3306) show slave hosts: Will not resolve empty hostname

Is that the case or am I missing something in the configuration? I tried browsing the code and I noticed that there's a section that tries to access the non-existant table mysql.slave_master_info table.

**Comment by shlomi-noach** [comment]
Do you use `"DiscoverByShowSlaveHosts": true` ? And if so, do you use `report-host`, `report-port` on your servers?

What does it show on `show slave hosts`?

**Comment by shlomi-noach** [comment]
To elaborate, if you don't have `report-host`, `report-port`, you should set `"DiscoverByShowSlaveHosts": false`

**Comment by rgallast** [comment]
Glad you pointed out the "show slave hosts". I added the report_host entry to the config files of the servers and that got rid of the message. Is there a forum for orchestrator? I wasn't sure about creating an issue if there was a forum. Thanks for the help!
