### ISSUE TITLE
go get returns error

### ISSUE THREAD

**Issue by BrianIp** [outbrain/orchestrator#263]
Trying to go get orchestrator returns an error:

```
~ go get github.com/outbrain/orchestrator/cmd/orchestrator
# cd /Users/brianip/Development/go/src/github.com/outbrain/orchestrator; git submodule update --init --recursive
fatal: No url found for submodule path 'vendor/github.com/martini-contrib/sessions' in .gitmodules
package github.com/outbrain/orchestrator/cmd/orchestrator: exit status 128
```

It looks like all that's missing is the .gitmodules file.

**Comment by shlomi-noach** [comment]
looking into

**Comment by shlomi-noach** [comment]
uh, what is it that you're trying to achieve with `git submodule update`?

fwiw, I did get rid of submodule information after it broke the `vendor` git.

**Comment by BrianIp** [comment]
I'm only running `go get`. I think internally go is running the `git submodule update`, so either the .gitmodules needs to be re-added or the submodules need to be removed for `go get` to work.

**Comment by shlomi-noach** [comment]
got it.
I'd say the official way of getting `orchestrator` is by `git clone`, but... I'll look into it.

**Comment by shlomi-noach** [comment]
Quick comment that I'm tackling this. Will get rid of the submodule info, as I do for all dependent libraries. Whether this is or isn't the right approach I'm unsure of yet. The entire go dependency issue is still something I don't feel I have the right solution for.

**Comment by shlomi-noach** [comment]
Got rid of this downstream. Will push upstream some time later.

**Comment by shlomi-noach** [comment]
This is fixed on https://github.com/github/orchestrator
