### ISSUE TITLE
Using orchestrator with Amazon Aurora

### ISSUE THREAD

**Issue by mysqldesu** [outbrain/orchestrator#274]
I am running MySQL clusters using a combination of MySQL instances on physical servers in a datacenter and Amazon Aurora. Using orchestrator is working well with the physical servers but I'm having trouble with the Amazon Aurora instances. There doesn't appear to be a way to have the Amazon Aurora to report-host at this point so there are always blanks when I run "show slave hosts" on the master. Also, the way in which change master host is performed on Amazon Aurora uses stored procedures instead of the normal change master command. Have you done any work to get orchestrator to work with Amazon Aurora instances?

**Comment by shlomi-noach** [comment]
I have no immediate plan to support Aurora. What I imagine this would imply is that `orchestrator` would need to support _hooks_ for many operations (`stop slave`, `start slave`, `change master to`, `reset master` and more). The user (you) would need to provide those hooks. This is possible, but more difficult to track and debug in the event of misconfiguration.

**Comment by mysqldesu** [comment]
Thanks for the information! Really appreciate all your efforts on orchestrator! It is a great tool.
