### ISSUE TITLE
Topology command out seconds_behind_master not slave_lag_seconds

### ISSUE THREAD

**Issue by bash99** [outbrain/orchestrator#275]
Hi, with version 0.5.6, I use pt-heartbeat to get percise lags and config slave_lag_query accordinglly.

```
mysql> select hostname, seconds_behind_master, slave_lag_seconds from database_instance;
+-----------------+-----------------------+-------------------+
| hostname        | seconds_behind_master | slave_lag_seconds |
+-----------------+-----------------------+-------------------+
| oltp_mysql_0244 |                     0 |                 0 |
| oltp_mysql_0245 |                   162 |                 0 |
```

But in topology output,
```
+ oltp_mysql_0244:3306 [0s,ok,5.7.14-8-log,rw,ROW,>>,GTID]
+ oltp_mysql_0245:3306 [162s,lag,5.7.14-8-log,ro,ROW,>>,GTID]
```

I think it should use slave_lag_seconds as output.

**Comment by shlomi-noach** [comment]
Did you configure [SlaveLagQuery](https://github.com/outbrain/orchestrator/blob/dcb6e1cc9560bb61742ef67279e8ad5972feb353/conf/orchestrator-simple.conf.json#L27) ?

**Comment by shlomi-noach** [comment]
BTW even if you have subsecond resolution right now, orchestrator still only measures replication lag in `second` granularity. This is subject to change.

**Comment by bash99** [comment]
@shlomi-noach 
Yes, I've config it.
  "SlaveLagQuery": "select ROUND(UNIX_TIMESTAMP() - UNIX_TIMESTAMP(ts) + 0.05) from test.heartbeat",

**Comment by shlomi-noach** [comment]
Confirmed this is happening. Will fix.

**Comment by shlomi-noach** [comment]
So, there are two valid ways to represent replication lag. I'm in favor of making the change, however it could also be argued that we should show the `Seconds_behind_master` value on the topology graph, as it represents the private lag of the specific replica (as opposed to accumulated lag, or _absolute_ lag, in case the replica is 2nd, 3rd or deeper level).

**Comment by shlomi-noach** [comment]
Fixed downstream; will push changes next week.
