### ISSUE TITLE
Hostnames show up in anonymous mode in "bubbles" with mouse-over in compact display. 

### ISSUE THREAD

**Issue by sjmudd** [outbrain/orchestrator#278]
If using anonymous mode and a compact display you can mouse over the different counts that are shown as "bubbles". When you do this the individual hostnames are shown and not replaced with an anonymise "instance-XX-YY" which might be expected.

Go to a URL like: https://somehost.example.com/web/cluster/clustername:3306?compact=true and then look at the bubbles where you see aggregated numbers. Mouse over the counters and see the full hostnames, not the anonymised ones.

Not a big deal but might be nice to fix.

**Comment by stevelippert** [comment]
I'm able to replicate this issue in my testing environment, see attached screenshot below.
![2016-11-11 12_57_43-orchestrator - mysql01](https://cloud.githubusercontent.com/assets/886585/20226666/9389f710-a80e-11e6-8bdf-22f1c11dbbc1.png)

**Comment by shlomi-noach** [comment]
Thank you both.
Fixed downstream, will merge later on.

**Comment by shlomi-noach** [comment]
This is fixed on https://github.com/github/orchestrator
