### ISSUE TITLE
Topology display error when skip_name_resolve is ON

### ISSUE THREAD

**Issue by bash99** [outbrain/orchestrator#280]
```
/usr/local/orchestrator/orchestrator -c which-master -i mysql-06:3306 cli
mysql-07:3306

/usr/local/orchestrator/orchestrator -c which-master -i mysql-07:3306 cli
mysql-06:3306

/usr/local/orchestrator/orchestrator -c topology -i mysql-06:3306 cli
mysql-06:3306 [0s,ok,5.1.73-log,rw,STATEMENT]

/usr/local/orchestrator/orchestrator -c topology -i mysql-07:3306 cli
mysql-07:3306 [0s,ok,5.1.73-log,rw,STATEMENT]
```

In the first hour, it's ok, after that, the replication display goes wrong.

**Comment by shlomi-noach** [comment]
Thank you --

- please use markdown's backticks for code snippets.

What is the reason the issue mentions `skip_name_resolve`? Did you try with/without and found that behavior only happens with `skip_name_resolve = ON`?

Also, what is `orchestrator`s config? Specifically, `HostnameResolveMethod`, `MySQLHostnameResolveMethod`?

Please add any other information which could be useful.

**Comment by bash99** [comment]
Sorry, I've found set MySQLHostnameResolveMethod to @@report_host solve this problem.

Yes, that behavior only happens with skip_name_resolve = On.
