### ISSUE TITLE
When Instance is in Maintenance, Reason is not displayed

### ISSUE THREAD

**Issue by leeparayno** [outbrain/orchestrator#291]
When an instance is in Maintenance Mode, the Reason is not displayed in the web display.

There is an icon that an instance is "In Maintenance", but the reason is not displayed.

Since the reason is required for the begin-maintenance command in the CLI, it would be helpful for other staff with access to the UI to be able to see the reason for the maintenance.

Perhaps also, demarcate the instances under maintenance with a separate box color as well to highlight instances under maintenance, as the wrench icon is fairly innocuous, IMO.

**Comment by leeparayno** [comment]
I did notice there was one occasion where an instance placed under maintenance was showing in the right side of the display, as a "Problem" where the reason was displayed, but I could not make that display/popup display on demand.

**Comment by shlomi-noach** [comment]
This is meanwhile fixed downstream.

**Comment by shlomi-noach** [comment]
Closing this; at some stage I will merge upstream
