### ISSUE TITLE
Unable to attach slaves to promoted master

### ISSUE THREAD

**Issue by mailankitkm** [outbrain/orchestrator#294]
We have done orchestrator setup done for 4 nodes as below.

![screenshot from 2016-11-24 14-10-04](https://cloud.githubusercontent.com/assets/23716764/20591657/ceabfb54-b24f-11e6-833a-c2c0b9f3d97c.png)

Now after promotion we are facing two issues.
1. we got new slave promoted as master however, other slave of old master made new cluster along with slaves replicating from it. Ideally, it should've started replication from newly promoted master.
![screenshot from 2016-11-24 14-15-13](https://cloud.githubusercontent.com/assets/23716764/20591857/a79e1172-b250-11e6-8692-04116750ea7f.png)
![screenshot from 2016-11-24 14-15-49](https://cloud.githubusercontent.com/assets/23716764/20591951/2f80eb00-b251-11e6-88fd-9cb516cd2df1.png)

2. we are getting error ("DeadMaster on hostname:3306 is blocked due to previous recovery") even after passing several minutes of last recovery. Current value of "RecoveryPeriodBlockSeconds": 0.

Complete config is attached. Please guide us.

> {
  "Debug": true,
  "EnableSyslog": false,
  "ListenAddress": ":3000",
  "MySQLTopologyUser": "orchestrator",
  "MySQLTopologyPassword": "orch!@#123",
  "MySQLTopologyCredentialsConfigFile": "",
  "MySQLTopologySSLPrivateKeyFile": "",
  "MySQLTopologySSLCertFile": "",
  "MySQLTopologySSLCAFile": "",
  "MySQLTopologySSLSkipVerify": true,
  "MySQLTopologyUseMutualTLS": false,
  "MySQLTopologyMaxPoolConnections": 3,
  "DatabaselessMode__experimental": false,
  "MySQLOrchestratorHost": "127.0.0.1",
  "MySQLOrchestratorPort": 3306,
  "MySQLOrchestratorDatabase": "orchestrator",
  "MySQLOrchestratorUser": "orchestrator",
  "MySQLOrchestratorPassword": "orch!@#",
  "MySQLOrchestratorCredentialsConfigFile": "",
  "MySQLOrchestratorSSLPrivateKeyFile": "",
  "MySQLOrchestratorSSLCertFile": "",
  "MySQLOrchestratorSSLCAFile": "",
  "MySQLOrchestratorSSLSkipVerify": true,
  "MySQLOrchestratorUseMutualTLS": false,
  "MySQLConnectTimeoutSeconds": 1,
  "DefaultInstancePort": 3306,
  "SlaveStartPostWaitMilliseconds": 1000,
  "DiscoverByShowSlaveHosts": true,
  "InstancePollSeconds": 5,
  "ReadLongRunningQueries": true,
  "UnseenInstanceForgetHours": 240,
  "SnapshotTopologiesIntervalHours": 0,
  "InstanceBulkOperationsWaitTimeoutSeconds": 10,
  "ActiveNodeExpireSeconds": 5,
  "HostnameResolveMethod": "default",
  "MySQLHostnameResolveMethod": "@@hostname",
  "SkipBinlogServerUnresolveCheck": true,
  "ExpiryHostnameResolvesMinutes": 60,
  "RejectHostnameResolvePattern": "",
  "ReasonableReplicationLagSeconds": 10,
  "ProblemIgnoreHostnameFilters": [],
  "VerifyReplicationFilters": false,
  "MaintenanceOwner": "orchestrator",
  "ReasonableMaintenanceReplicationLagSeconds": 20,
  "MaintenanceExpireMinutes": 10,
  "MaintenancePurgeDays": 365,
  "CandidateInstanceExpireMinutes": 60,
  "AuditLogFile": "",
  "AuditToSyslog": false,
  "AuditPageSize": 20,
  "AuditPurgeDays": 365,
  "RemoveTextFromHostnameDisplay": ".mydomain.com:3306",
  "ReadOnly": false,
  "AuthenticationMethod": "",
  "HTTPAuthUser": "",
  "HTTPAuthPassword": "",
  "AuthUserHeader": "",
  "PowerAuthUsers": [
    "*"
  ],
  "ClusterNameToAlias": {
    "dawslmktdb": "Test_Cluster"
  },
  "SlaveLagQuery": "",
  "DetectClusterAliasQuery": "SELECT 'TEST_CLUSTER'",
  "DetectClusterDomainQuery": "",
  "DetectInstanceAliasQuery": "",
  "DetectPromotionRuleQuery": "",
  "DataCenterPattern": "[.]([^.]+)[.][^.]+[.]mydomain[.]com",
  "PhysicalEnvironmentPattern": "[.]([^.]+[.][^.]+)[.]mydomain[.]com",
  "PromotionIgnoreHostnameFilters": [],
  "DetectSemiSyncEnforcedQuery": "",
  "ServeAgentsHttp": false,
  "AgentsServerPort": ":3001",
  "AgentsUseSSL": false,
  "AgentsUseMutualTLS": false,
  "AgentSSLSkipVerify": false,
  "AgentSSLPrivateKeyFile": "",
  "AgentSSLCertFile": "",
  "AgentSSLCAFile": "",
  "AgentSSLValidOUs": [],
  "UseSSL": false,
  "UseMutualTLS": false,
  "SSLSkipVerify": false,
  "SSLPrivateKeyFile": "",
  "SSLCertFile": "",
  "SSLCAFile": "",
  "SSLValidOUs": [],
  "URLPrefix": "",
  "StatusEndpoint": "/api/status",
  "StatusSimpleHealth": true,
  "StatusOUVerify": false,
  "HttpTimeoutSeconds": 60,
  "AgentPollMinutes": 60,
  "AgentAutoDiscover": false,
  "UnseenAgentForgetHours": 6,
  "StaleSeedFailMinutes": 60,
  "SeedAcceptableBytesDiff": 8192,
  "PseudoGTIDPattern": "",
  "PseudoGTIDPatternIsFixedSubstring": false,
  "PseudoGTIDMonotonicHint": "asc:",
  "DetectPseudoGTIDQuery": "",
  "PseudoGTIDCoordinatesHistoryHeuristicMinutes": 2,
  "BinlogEventsChunkSize": 10000,
  "BufferBinlogEvents": true,
  "SkipBinlogEventsContaining": [],
  "ReduceReplicationAnalysisCount": true,
  "FailureDetectionPeriodBlockMinutes": 3, 
  "RecoveryPollSeconds": 5,
  "RecoveryPeriodBlockSeconds": 0,
  "RecoveryIgnoreHostnameFilters": [],
  "RecoverMasterClusterFilters": [
    "dawslmkt"
  ],
  "RecoverIntermediateMasterClusterFilters": [
    "_intermediate_master_pattern_"
  ],
  "OnFailureDetectionProcesses": [
    "echo 'Detected {failureType} on {failureCluster}. Affected replicas: {countSlaves}' >> /tmp/recovery.log"
  ],
  "PreFailoverProcesses": [
    "echo 'Will recover from {failureType} on {failureCluster}' >> /tmp/recovery.log"
  ],
  "PostFailoverProcesses": [
    "echo '(for all types) Recovered from {failureType} on {failureCluster}. Failed: {failedHost}:{failedPort}; Successor: {successorHost}:{successorPort}' >> /tmp/recovery.log"
  ],
  "PostUnsuccessfulFailoverProcesses": [],
  "PostMasterFailoverProcesses": [
    "echo 'Recovered from {failureType} on {failureCluster}. Failed: {failedHost}:{failedPort}; Promoted: {successorHost}:{successorPort}' >> /tmp/recovery.log"
  ],
  "PostIntermediateMasterFailoverProcesses": [
    "echo 'Recovered from {failureType} on {failureCluster}. Failed: {failedHost}:{failedPort}; Successor: {successorHost}:{successorPort}' >> /tmp/recovery.log"
  ],
  "CoMasterRecoveryMustPromoteOtherCoMaster": true,
  "DetachLostSlavesAfterMasterFailover": false,
  "ApplyMySQLPromotionAfterMasterFailover": true,
  "MasterFailoverDetachSlaveMasterHost": true,
  "MasterFailoverLostInstancesDowntimeMinutes": 0,
  "PostponeSlaveRecoveryOnLagMinutes": 0,
  "OSCIgnoreHostnameFilters": [],
  "GraphiteAddr": "",
  "GraphitePath": "",
  "GraphiteConvertHostnameDotsToUnderscores": true
}

**Comment by shlomi-noach** [comment]
I don't see your servers using GTID or Pseudo-GTID. To run recoveries you should have either running (this is documented).

An MHA-like solution is being experimented with, but that's a more complex setup where you'd have to run agents on your boxes.

Pseudo-GTID is easy to set up, please consider https://github.com/outbrain/orchestrator/wiki/Orchestrator-Manual#pseudo-gtid

Without some form of unique values in the binary log, it is more difficult and time consuming to coordinate binary log entries cross servers. Pseudo-GTIDs make the process reliable, and easy to work with given that some replicas could be significantly lagging behind; with Pseudo-GTID you can quickly skip to older binary logs to find correlated coordinates.

**Comment by mailankitkm** [comment]
Thanks for your quick reply, really appreciated !
 
We have just implemented Pseudo GTID and it worked great. Now, We're having another issue that is when master mysql goes down, it generates two event very quickly (1) UnreachableMasterWithStaleSlaves -> 2) DeadMaster) that can be seeing in below screenshot. 

We expect that whenever master goes into State : UnreachableMasterWithStaleSlaves it should start promoting slave but it is not starting until it gets the second event DeadMaster. On this event it is not promoting master until we acknowledge the first event by ourself.

![screenshot from 2016-11-24 17-21-16](https://cloud.githubusercontent.com/assets/23716764/20597560/7267b02a-b26a-11e6-9255-cb57d68f59d6.png)

Below values are being used currently.
"FailureDetectionPeriodBlockMinutes": 5,
"RecoveryPeriodBlockSeconds": 180,

**Comment by shlomi-noach** [comment]
`UnreachableMasterWithStaleSlaves` is not a trigger for recovery. This a gray area where the state could be or not be eligible for failover. I leave it as it is for now.
`DeadMaster` should kick in, unless:
- you have a previous recovery unacknowledged in the last `180` seconds, as per your configuration
- the server is "downtime"d.

> until we acknowledge the first event

You're not acknowledging the `UnreachableMasterWithStaleSlaves` event here. What you'r acknowledging is the previous failover.

**Comment by mailankitkm** [comment]
Many Thanks. It really helped a lot and saved our time.
