### ISSUE TITLE
hostname show  truncate

### ISSUE THREAD

**Issue by linuxgood1230** [outbrain/orchestrator#296]
```
host1:  xx-dd34.zw:333333
host2:  dd-24.zw:33333
```

Then ,host show name is :  
```
host1: xx-dd3
host2: dd-2
```

the same suffix  truncated

```
function commonSuffixLength(strings) {
  if (strings.length == 0) {
    return 0;
  }
  if (strings.length == 1) {
    return 0;
  }
  var longestSuffixLength = 0;
  var maxLength = 0;
  strings.forEach(function(s) {
    maxLength = ((maxLength == 0) ? s.length : Math
      .min(maxLength, s.length));
  });
  var suffixLength = 0;
  while (suffixLength < maxLength) {
    suffixLength++
    var suffixes = strings.map(function(s) {
      return s.substring(s.length - suffixLength)
    });
    var uniqueSuffixes = suffixes.filter(function(elem, pos) {
      return suffixes.indexOf(elem) == pos;
    })
    if (uniqueSuffixes.length > 1) {
      // lost it. keep last longestSuffixLength value
      break;
    }
    // we're still good
    longestSuffixLength = suffixLength;
  }
  return longestSuffixLength;
}
```

**Comment by shlomi-noach** [comment]
Thank you. First, I'd like to encourage you to use markdown to format your messages, or else they're hard to read. Please see how I've edited your original message.

In addition, please clarify where you see the problem (e.g. in your case: on web interface)

This behavior is intentional: we try to save up on screen pixels; hostnames tend to be very long.

**Comment by linuxgood1230** [comment]
Thank you
You have multi data center . Maybe your all hosts have the same suffix.So you can cut off.

**Comment by shlomi-noach** [comment]
Can you please  parity the problem you have? Your expectation?

**Comment by shlomi-noach** [comment]
sorry, typo, Can you please clarify the problem you have? Your expectation?

**Comment by shlomi-noach** [comment]
I'm actually in favor of getting rid of `commonSuffixLength`. We have the `RemoveTextFromHostnameDisplay` config variable instead.

**Comment by shlomi-noach** [comment]
This is fixed downstream. Will merge later.

**Comment by shlomi-noach** [comment]
This is fixed in https://github.com/github/orchestrator, the new upstream for this project.
