### ISSUE TITLE
GUI and CLI Make Co-Master issue with replication user

### ISSUE THREAD

**Issue by leeparayno** [outbrain/orchestrator#297]
I've tried to use the make-co-master feature on a Master-Replica server topology, and both the Web UI and the CLI fail with the Master failing to start it's slave IO thread, due to the replication user/password not being set:

Fatal error: Invalid (empty) username when attempting to connect to the master server. Connection attempt terminated.

I didn't find any configuration option to specify the replication user that should be used by Orchestrator to specify when it issues the CHANGE MASTER command, to the instances on instances that do not have a current replication configuration.

**Comment by shlomi-noach** [comment]
Please see https://github.com/outbrain/orchestrator/issues/81

**Comment by leeparayno** [comment]
Thanks Shlomi, changing master_info_repository to TABLE worked.
