### ISSUE TITLE
Privilege Error

### ISSUE THREAD

**Issue by elgabito** [outbrain/orchestrator#32]
I ran the grants as indicated in the documentation, but I get the following error:

2014-08-14 15:05:03 ERROR Error 1227: Access denied; you need (at least one of) the REPLICATION SLAVE privilege(s) for this operation

This is the result of my "show grant":
GRANT PROCESS, SUPER ON *.* TO 'orchestrator_act'@'drgordbreport' IDENTIFIED BY PASSWORD 'hashedpassword'

Perhaps the documentation is out of date for the latest release?

Edit: This seems to occur even if I add the "replication slave" privilege.

**Comment by shlomi-noach** [comment]
closing due to long time having passed
