### ISSUE TITLE
orchestrator master accumulating tcp connections until it freeze

### ISSUE THREAD

**Issue by shahar-fleischman** [outbrain/orchestrator#37]
hi,

orchestrator master is freezing after around 20 hours from restart.
the number of EST TCP connections at that point is around 20k.
removing SSL did not help.

thanks.
shaharf.

**Comment by shahar-fleischman** [comment]
hey,

tried the new version, and the results are worst, it takes 8 hours to freeze instead of 20 in the previous version.

**Comment by shlomi-noach** [comment]
Well that's a hint I guess.

**Comment by shahar-fleischman** [comment]
hi, 

just looked at file => orchestrator/agent/agent_dao.go, and i see the a line in it:
var httpTimeout = time.Duration(time.Duration(config.Config.HttpTimeoutSeconds) * time.Second)
should it get the value from orchestrator.conf.json, or from orchestrator/config/config.go ?

**Comment by shlomi-noach** [comment]
Both. If not found in conf file then default value is taken from config.go.
The latest change I made disables th etimeout altogether on non-ssl connections, in the assumption that the transport object is what prevents golang from reusing connections. Based on your private note that now things are made worse I see this is not the case.

**Comment by shahar-fleischman** [comment]
trying version 1.2.16, will know by EOD if this helped.

**Comment by shahar-fleischman** [comment]
the rate it much slower with the new version, after 4 hours it on has 75 EST TCP connections.
so we might be in the clear.
will update tomorrow.

**Comment by shlomi-noach** [comment]
Great!

**Comment by shahar-fleischman** [comment]
still working after 2 days, this is a lot better.
it has 3800 open TCP connections after 2 days, so not solved but a lot better.

**Comment by shlomi-noach** [comment]
OK, so still leaking...
I'm going to stop working on this for now and leave the issue open, given
that the leakage is slow.

On Tue, Jan 6, 2015 at 10:12 AM, shahar-fleischman <notifications@github.com

**Comment by shahar-fleischman** [comment]
by current leakage of 6% file descriptors used per 2 days, it should hold for around 8 days until it dies(dies when it reaches 28% used file descriptors).
well, it is better than 20 hours :)
10x.

**Comment by shlomi-noach** [comment]
It will be interesting to see whether it accumulates in constant rate;
please update by the end of the week

On Tue, Jan 6, 2015 at 11:41 AM, shahar-fleischman <notifications@github.com

**Comment by shahar-fleischman** [comment]
dies after 7 days at a time.
