### ISSUE TITLE
If possible add a mouse over describing the dots in .../web/clusters/

### ISSUE THREAD

**Issue by sjmudd** [outbrain/orchestrator#41]
The line with instances shows up to 4 dots which seem to represent: total servers in the cluster, warning critical and not available.
* It might be nice if a mouse-over describes this a little more completely to avoid us looking it up in the docs
* It might also be nice to be able to click on these dots and see only these servers (so we can find out more details about the problem etc).

**Comment by shlomi-noach** [comment]
On viewing a cluster's page, the Problems drop down (on the right) only shows problems of that cluster. This roughly covers your second request.
