### ISSUE TITLE
Add a /health URL that returns JSON with the health of the app as a whole

### ISSUE THREAD

**Issue by silviabotros** [outbrain/orchestrator#44]
This is a common pattern in ops deployment of applications. Usually it would be a /health URL that returns, when healthy, return code 200 and a JSON showing all the things it checked. In orchestrator's case it would be a JSON that would look like this

```
{"orchestrator": "ok", "orchestrator_mysql": {"orchestrator_mysql_running": "ok", "orchestrator_mysql_query": "ok"}}
```

This would greatly simplify the task of monitoring orchestrator in any given infrastructure

**Comment by shlomi-noach** [comment]
pushed in 1.3.10

**Comment by silviabotros** [comment]
Thank you!
