### ISSUE TITLE
Cluster visual representation broken in safari yosemite

### ISSUE THREAD

**Issue by silviabotros** [outbrain/orchestrator#53]
Looks like a javascript error only in Safari yosemite as far as I can tell (Don't have a machine with other than yosemite to test older safaris)

The error in the console is
```
TypeError: undefined is not a function (evaluating 'clusters.forEach')
```
pointing to orchestrator.js, line 522

All I get for the cluster is this
![screenshot 2015-03-23 11 28 00](https://cloud.githubusercontent.com/assets/1323210/6783366/b28834ac-d14f-11e4-91a6-0d518b9fef4a.png)

Using chrome is the current workaround

**Comment by shlomi-noach** [comment]
Currently Firefox & Chrome are supported, with no immediate plans to support Safari. There are no plans at all to support IE.

**Comment by shlomi-noach** [comment]
I'm closing this as I don't intend to support Safari at this stage.

**Comment by grypyrg** [comment]
Booo for the non-safari-support! :)
