### ISSUE TITLE
Handle delayed slaves better

### ISSUE THREAD

**Issue by dveeden** [outbrain/orchestrator#59]
A slave with a 3600s delay should not be seen as a problem.

It currently says "3613 seconds lag". This could be changed in "3600 seconds delay, 13 seconds lag"
This would make it easier to see if a delayed slave is lagging behind.

The SQL_Delay column of show slave status could probably be used to detect this.

**Comment by shlomi-noach** [comment]
Solved. When SQL_Delay is set, orchestrator will expect no more than +/-10 seconds difference between lag & SQL_Delay. If within these boundaries, it will not mark as warning/lag.
