### ISSUE TITLE
Repository is not "go-gettable"

### ISSUE THREAD

**Issue by dgryski** [outbrain/orchestrator#60]
The current build setup requires augmenting `GOPATH` and also hard-codes `/usr/share/golang`.  Orchestrator should either vendor its dependencies (via something like `godep`), or more fully integrate into the Go environment on the host machine.

This can be done with a single commit: 
` git mv src/github.com/outbrain/orchestrator/* .`

**Comment by shuhaowu** [comment]
Are there any plans to merge this if I can submit a PR? I can relatively easily fix this and make sure the build script still functions.

cc: @shlomi-noach

**Comment by shlomi-noach** [comment]
If there's a PR then I'll make plans to merge this :)
I'll be pushing some more uncommitted or locally committed changes tomorrow/Friday FYI

**Comment by dgryski** [comment]
The PR is literally the one command I listed above. Build scripts are extra.  Poke me tomorrow and I'll submit one when you want it.

**Comment by shlomi-noach** [comment]
Erm... missed that one :P
Sure, will apply.

**Comment by shlomi-noach** [comment]
Thanks @shuhaowu @dgryski
