### ISSUE TITLE
How to disable hostname resolve

### ISSUE THREAD

**Issue by wyhysj** [outbrain/orchestrator#62]
Hi, when I enter the discovery mode, entered IP:Port, it will do a cname lookup, how can I disable it, because my hostname is not standardised, I want to skip the hostname lookup

Is it possible to do?

**Comment by shlomi-noach** [comment]
in your config, set
```
  "HostnameResolveMethod": "none",
```

**Comment by wyhysj** [comment]
Hi, I tried that, it didn't work

Here's my log

2015-05-14 12:04:51 ERROR dial tcp: lookup db-test-slave-xx-xx-xx-xx: no
such host


My configuration file


...

  "ActiveNodeExpireSeconds": 20,

  "HostnameResolveMethod": "none",

  "ExpiryHostnameResolvesMinutes": 0,

...

**Comment by shlomi-noach** [comment]
There is an additional resolve, which is not a cname resolve: once connected to a mysql server, orchestrator issues a SELECT @@hostname; and from then on uses that. 
I take it you do not have DNS at all? Are your slaves connecting to the master host using ip only? Is everything managed via ip only?

**Comment by wyhysj** [comment]
yes, we don't use DNS to resolve MySQL host, via ip only, so all slaves connect to the master IP.

**Comment by shlomi-noach** [comment]
So right now This is not supported, but can be. I'm leaving this issue open and maybe I can do a resolve-to-ip or something.

**Comment by wyhysj** [comment]
Thanks, hope to see your update

**Comment by silviabotros** [comment]
Realized i have the same problem, granted my setup in this case isn't conventional.

I have hosts where each box hosts 5 instances, each with a dedicated VIP. Each VIP has an A record that extends the host's A record
```
Host: hostname.organization.net
shard00: s00.hostname.organization.net
shard01: s01.hostname.organization.net
```

And so on. This is the output I get when In try to discover now of these shards. Same results regardless of using the shard DNS record or straight IPs

```
[root@orchestrator0001p1mdw1 ~]# /usr/local/orchestrator/orchestrator -verbose -stack -c discover -i 10.42.241.177:3306
2015-05-21 14:18:46 INFO starting
2015-05-21 14:18:46 INFO Read config: /etc/orchestrator.conf.json
2015-05-21 14:18:46 INFO Starting discovery at {Hostname:10.42.241.177 Port:3306}
10.42.241.177:3306
```

Nothing appears in the dashboard so I try again. On second attempt I get this

```
[root@orchestrator0001p1mdw1 ~]# /usr/local/orchestrator/orchestrator -verbose -stack -c discover -i 10.42.241.177:3306
2015-05-21 14:20:27 INFO starting
2015-05-21 14:20:27 INFO Read config: /etc/orchestrator.conf.json
2015-05-21 14:20:27 INFO Starting discovery at {Hostname:dbshort0005p1mdw1.sendgrid.net Port:3306}
2015-05-21 14:20:27 ERROR dial tcp 10.42.241.154:3306: connection refused
/usr/share/golang/src/github.com/outbrain/golib/log/log.go:111 (0x45ca11)
/usr/share/golang/src/github.com/outbrain/golib/log/log.go:157 (0x45d20d)
/usr/share/golang/src/github.com/outbrain/golib/sqlutils/sqlutils.go:209 (0x609fcd)
/home/snoach/dev/openark/orchestrator/src/github.com/outbrain/orchestrator/inst/instance_dao.go:150 (0x4d15f8)
/home/snoach/dev/openark/orchestrator/src/github.com/outbrain/orchestrator/logic/orchestrator.go:73 (0x50a45d)
/home/snoach/dev/openark/orchestrator/src/github.com/outbrain/orchestrator/logic/orchestrator.go:51 (0x511ac9)
/usr/local/go/src/runtime/asm_amd64.s:2232 (0x428031)
2015-05-21 14:20:27 ERROR dial tcp 10.42.241.154:3306: connection refused
/usr/share/golang/src/github.com/outbrain/golib/log/log.go:111 (0x45ca11)
/usr/share/golang/src/github.com/outbrain/golib/log/log.go:157 (0x45d20d)
/home/snoach/dev/openark/orchestrator/src/github.com/outbrain/orchestrator/inst/instance_dao.go:371 (0x4d14b8)
/home/snoach/dev/openark/orchestrator/src/github.com/outbrain/orchestrator/logic/orchestrator.go:73 (0x50a45d)
/home/snoach/dev/openark/orchestrator/src/github.com/outbrain/orchestrator/logic/orchestrator.go:51 (0x511ac9)
/usr/local/go/src/runtime/asm_amd64.s:2232 (0x428031)
2015-05-21 14:20:27 WARNING instance is nil in DiscoverInstance. key={Hostname:dbshort0005p1mdw1.sendgrid.net Port:3306}, error=dial tcp 10.42.241.154:3306: connection refused
dbshort0005p1mdw1.sendgrid.net:3306
```

On inspecting one of the shards shows this
```
mysql> select @@hostname;
+--------------------------------+
| @@hostname                     |
+--------------------------------+
| hostname.organization.net |
+--------------------------------+
```

I am looking into fixing my reported hostname in these instances

**Comment by shlomi-noach** [comment]
have sanitized most data in the above comment.

**Comment by silviabotros** [comment]
According to https://dev.mysql.com/doc/refman/5.5/en/server-system-variables.html#sysvar_hostname
The value of ```select @@hostname;``` isn't something we can configure. So relying on that output in discovery essentially excludes situations where the one host is running multiple instances using VIPs not the primary IP on the box/what the host resolves to

**Comment by shlomi-noach** [comment]
Ok, I can have configuration to skip the use of @@hostname. I didn't think of this use case.

**Comment by shlomi-noach** [comment]
Please try https://github.com/outbrain/orchestrator/releases/tag/v1.4.129
And config as follows:
    "HostnameResolveMethod": "none",

Also configure the new "MySQLHostnameResolveMethod" to either:
- "@@hostname" (current, default, should work for most people but not for @wyhysj and @silviabotros )
- "@@report_host" -- this means you must configure the `report_host` variable in `my.cnf` and _orchestrator_ will accept this value as the definitive truth -- so this cleanly moves the problem under your own control. 
- "none" -- and I have not the slightest idea how it would work in your case.

So for @wyhysj and @silviabotros , use:
    "MySQLHostnameResolveMethod": "@@hostname",

Please let me know how goes.

**Comment by wyhysj** [comment]
Hi shlomi

There's a issue when discovering cluster

```
[martini] Started GET /api/discover/10.10.16.206/6606 for 10.10.16.236:50351
2015-05-26 08:11:11 DEBUG Hostname unresolved yet: 10.10.16.206
2015-05-26 08:11:11 DEBUG Cache hostname resolve 10.10.16.206 as 10.10.16.206
[martini] Completed 200 OK in 1.391503ms
2015-05-26 08:11:11 INFO Starting discovery at {Hostname:10.10.16.206 Port:6606}
2015-05-26 08:11:11 ERROR sql: Scan error on column index 1: unsupported driver -> Scan pair: <nil> -> *string
2015-05-26 08:11:11 WARNING instance is nil in DiscoverInstance. key={Hostname:10.10.16.206 Port:6606}, error=sql: Scan error on column index 1: unsupported driver -> Scan pair: <nil> -> *string
2015-05-26 08:11:14 DEBUG outdated keys: []
```

By the way, you mean for us configure MySQLHostnameResolveMethod to "@@report_host" ? It's a little confused in your last comment.

**Comment by silviabotros** [comment]
@wyhysj yes. Add this to your config file in ```/etc/orchestrator.conf.json```

```"HostnameResolveMethod": "@@report_host"```

Restart orchestrator, then attempt the discovery. I just tested this in my staging environment and it worked.

**Comment by wyhysj** [comment]
@silviabotros @shlomi-noach 

Still can not

Same error below:

```
2015-05-26 10:43:53 ERROR sql: Scan error on column index 1: unsupported driver -> Scan pair: <nil> -> *string
2015-05-26 10:43:53 WARNING instance is nil in DiscoverInstance. key={Hostname:10.10.16.206 Port:6606}, error=sql: Scan error on column index 1: unsupported driver -> Scan pair: <nil> -> *string
```

Configuration
```
  "HostnameResolveMethod": "none",
  "MySQLHostnameResolveMethod": "@@report_host",
```

**Comment by shlomi-noach** [comment]
@wyhysj , I suspect your `@@report_host` variable is not configured, in which case it is `NULL`.
I'm fixing the orchestrator code to gracefully handle this case, but it will still not do what you want it to do. You must first configure this variable. Unfortunately, MySQL requires a restart since this is a read-only variable.

Meanwhile, I'm further considering resolving to an IP, which might also work out for you.

**Comment by shlomi-noach** [comment]
This release: https://github.com/outbrain/orchestrator/releases/tag/v1.4.130 gracefully notifies when `@@report_host` is `NULL`

**Comment by wyhysj** [comment]
Sorry, I thought report_host is all configured, I checked some of my cluster is not properly configured including this one

It works, and hence update to 1.4.130, can see the reason from console log

Thanks @shlomi-noach

**Comment by shlomi-noach** [comment]
@wyhysj @silviabotros  Please also upgrade to https://github.com/outbrain/orchestrator/releases/tag/v1.4.131
as I've found an issue with infinite hostname resolves with `@@report_host`.

**Comment by wyhysj** [comment]
@shlomi-noach Noted with Thanks

**Comment by shlomi-noach** [comment]
@wyhysj @silviabotros can you confirm latest version solves this issue?

**Comment by wyhysj** [comment]
Hi @shlomi-noach 

Sorry, last week was on vacation

Just test the latest version, issue resolved

Thanks

**Comment by shlomi-noach** [comment]
Excellent! Thanks; closing issue
