### ISSUE TITLE
Provide a way to see the configuration behaviour of orchestrator if a master or intermediate master fails

### ISSUE THREAD

**Issue by sjmudd** [outbrain/orchestrator#66]
Orchestrator is designed to be able to re-arrange servers if there's a failure of your primary master or an intermediate master.
Currently the decision as to whether this is to be "automated", or it should just warn you does not appear to be visible in the GUI as it's configured in a configuration file.
From the point of view of a user using the GUI it's good to know if orchestrator is going to attempt this automatic recovery or not, so exposing this configuration setting, and potentially making it changeable via the GUI seems like a convenient thing to do.

Please consider adding this functionality at a time that is convenient.

Thanks,

Simon

**Comment by shlomi-noach** [comment]
currently supported via api:

```/api/automated-recovery-filters```

**Comment by shlomi-noach** [comment]
Now visible in GUI, see (i) icon on left in cluster page
