### ISSUE TITLE
Add an indicator in the UI if logged in read only mode or not

### ISSUE THREAD

**Issue by silviabotros** [outbrain/orchestrator#68]
Just an enhancement to User experience. It would be great if orchestrator showed in the UI when it is in read only mode. Similarly, if using Proxy login, showing the username one is logged in as.

**Comment by shlomi-noach** [comment]
will do

**Comment by shlomi-noach** [comment]
available in https://github.com/outbrain/orchestrator/releases/tag/v1.4.157
