### ISSUE TITLE
Architectural impediments to Percona/Oracle GTID support?

### ISSUE THREAD

**Issue by jasonhl** [outbrain/orchestrator#70]
More of a question than an issue: Are there any architectural/structural issues in Orchestrator that would prevent the tool from supporting 5.6 style GTIDs? We are on 5.6 in "classic" replication mode right now and are looking hard at GTIDs. We'd love to be able to use Orchestrator for cluster management and so are wondering how much work it would be to teach it how to handle "real" GTIDs.

From the docs/presentations I've seen, it looks like this support was never needed so it was just never implemented. If that's the case and it's "just work", then that's fine. My question is more about whether there are baked in assumptions which would make implementing this support difficult.

@shlomi-noach

**Comment by shlomi-noach** [comment]
Hi,
Correct. This was never implemented. I have started to added support for GTID, but there are various delicate issues which need to be thought of.
In particular, the fact that a topology, which all members configured with gtid_mode=1, does not necessarily have to use gtid. A slave may or may not choose to use AUTO_POSITION. This is still easy to work out on single move-up, move-below -type commands, but way more difficult to coordinate when you need to move a bulk of slaves (e.g. in a crash recovery scenario) and some of them do have auto-position enabled, and some don't. One such complication is the problem of reliably comparing the positions of all slaves. 
My current thought is that whenever gtid is enabled, just fallback on the most naive solution, and avoid all the benefits obtained by pseudo-gtid, such as bucketing and parallelizing on bulk operations. I guess for most users this is just fine.
Anyway I don't have a plan on when this will be production ready. We have more urgent matters to attend to. We are using GTID, but on a fraction of our topologies.

**Comment by jasonhl** [comment]
Thanks for the quick answer @shlomi-noach :-)

>In particular, the fact that a topology, which all members configured with gtid_mode=1, does not necessarily have to use gtid. A slave may or may not choose to use AUTO_POSITION.

Would it be reasonable, as a first pass, to simply state that Orchestrator will work with all GTIDs or no GTIDs and basically declare this "mixed mode" as unsupported? Would you accept patches in that direction?

**Comment by shlomi-noach** [comment]
I don't wish to start with "supports all or nothing" as this would imply
duplicate work and will very shortly be abandoned. I would rather sovle it
the correct way.
You're welcome to give a hand in applying patches!

**Comment by shlomi-noach** [comment]
GTID (Oracle & MariaDB) is supported as of https://github.com/outbrain/orchestrator/releases/tag/v1.4.334
