### ISSUE TITLE
Make orchestrator reload config with SIGHUP when running as a daemon

### ISSUE THREAD

**Issue by sjmudd** [outbrain/orchestrator#71]
Many unix daemons will reload their config if you send them SIGHUP.
This is handy as it's easy to do via scripting etc.
Orchestrator has an API to do that but it requires a bit more effort (using the web interface), so I'd like to see it also responding to SIGHUP and reloading the configuration.

This integrates better with configuration management systems when the config file may be pushed out and we want orchestrator to pick this up.

**Comment by shlomi-noach** [comment]
Supported in 1.4.172 (not yet released)
`kill -HUP` causes config.Reload
also supported by
`sudo /etc/init.d/orchestrator reload`
