### ISSUE TITLE
provide way to see active master in orchestrator cluster.

### ISSUE THREAD

**Issue by sjmudd** [outbrain/orchestrator#72]
If you have a cluster of orchestrator boxes there's a URL to find the current "active master": https://some.host.com/api/health

However, there appears to be no direct link from the main dashboard to query that info directly from the GUI (no button to press to get there). Remembering the URL is hard so if you can find a way to show this setting that would be good.

**Comment by shlomi-noach** [comment]
Clarification: this request is to show the active orchestrator node.

**Comment by shlomi-noach** [comment]
available in v1.4.180
see `/web/status`
