### ISSUE TITLE
Provide pointer to where to find details logs on the active orchestrator server

### ISSUE THREAD

**Issue by sjmudd** [outbrain/orchestrator#73]
Orchestrator may have trouble moving master about and give you a message on the web interface.

e.g. Something like: "2015-06-28 10:35:04 ERROR Mismatching entries, aborting: BEGIN GTID 0-123210030-19291 <-> BEGIN GTID 0-123210030-19291 cid=6429261944"

The error message is fine but we probably now need to go and debug what happened etc so maybe pointing to the location of a more detailed error log in the same message would be good.

So just add the text: "More detailed logging can be found on host134.example.com:/var/log/orchestrator/some.log"

If you can provide such an additional message it makes it easier to go and find out what happened.
In this particular failure case it wasn't clear what the "current status" was. Had the server been moved? Had it been put back where it was again? or where things just completely broken?

Things did not seem so bad after all but an additional helpful message/hint as to the final state of the requested (failed) change would be nice.

**Comment by shlomi-noach** [comment]
The logfile is written by the daemon (orchestrator writes to stdout and daemon redirects to file).
This would be `/var/log/orchestrator.log` unless modified (and it is not modified in our case).
So this boils down to "which is the active orchestrator app node", which is https://github.com/outbrain/orchestrator/issues/72

With regard what the status is, the audit is the correct place to look for; also orchestrator does its best to rollback any failed operation. I do not with to start logging out tons of info to the screen. Audit is a good place.
