### ISSUE TITLE
Please log usernames in https://orchestrator.example.com/web/audit

### ISSUE THREAD

**Issue by sjmudd** [outbrain/orchestrator#74]
The url provides an audit log which is good but currently does not seem to log the username who connected. If there's more than one person using orchestrator it might be handy to log the username where this is know so we can figure out "who" triggered different actions.

**Comment by shlomi-noach** [comment]
Orchestrator does not operate like database servers, in that users are connected via dedicated credentials/connections. The web/API is just HTTP based. 
I do have user authentication (as you already know) but I do not support right now the mechanism to pass user info throughout any given operation. Most orchestrator does not have the notion of a "Session".
I'm unsure at this stage what would be the best way to pass on the invoking username to all possible commands.

**Comment by shlomi-noach** [comment]
No action will be taken on this issue.
