### ISSUE TITLE
Orchestrator tries to do SHOW BINLOG EVENTS IN '' (empty string)

### ISSUE THREAD

**Issue by dveeden** [outbrain/orchestrator#76]
For a match below from the web GUI it tries to do this:
```
show binlog events in '' FROM 0 LIMIT 10000
```

This is not a valid command.

**Comment by shlomi-noach** [comment]
Of course I will have to investigate the root cause (already in progress), but at any case I added sanity checks that would fail on such situation (and would certainly not go into infinite loop).

**Comment by shlomi-noach** [comment]
This does not happen anymore
