### ISSUE TITLE
Make the discovery page show the results of requesting searching for servers.

### ISSUE THREAD

**Issue by sjmudd** [outbrain/orchestrator#88]
Currently once you add a hostname to "discover" you don't get any feedback on whether it worked or did not.  Network access may mean that Orchestrator can not actually reach the desired host but this won't be visible.

So I'd like to see some sort of list of "notifications" on the top of the web/discover page which indicates the results of the requests.

e.g.

(coloured green=success) Discovery of server-0001.example.com:3306 succeeded (found MySQL 5.6.7, uptime XXX seconds)     X  (the X to close the notification and indicate it's read)
(coloured red=failure) Discovery of server-0009.example.com:3366 failed (could not reach host [some reason if known, maybe not found, or credentials don't work])   X

etc.

This would make the process much more transparent.

**Comment by shlomi-noach** [comment]
discovery is now synchronous on `/api/discover` and `discover` command, as of 1.4.241
Not showing yet in web page

**Comment by shlomi-noach** [comment]
Notification area now clearly indicates whether discovery of instance has been successful or not. If successful, provides a link to found instance
