### ISSUE TITLE
One Slave not getting discovered.

### ISSUE THREAD

**Issue by gautamsomani** [outbrain/orchestrator#93]
Have a master with around 7 slaves. All were showing earlier. Master was changed, after which discover command was re-issued. All slaves showed up, except one. "Topology" command also does not shows this slave.

In database_instance table of orchestrator DB, there is no record for this slave host. On the slave host, there is no connection from orchestrator. Orchestrator is able to connect to port 3306 of the slave, confirmed by using the "resolve" command, by using mysql client command and also by telnet. 

Slave is replicating from master and slave host has the orchestrator user and password with proper privileges for the orchestrator tool to connect.

What else should I check?

**Comment by shlomi-noach** [comment]
Please grab latest binary of orchestrator. Last week I modified the
"discover" command to be synchronous.
Fromh e orchestrator host, please issue "orchestrator -c discover -i
slave.hostname --debug"
See what comes out. Feel free to post the output here.

Also, what is your config's hostname resolve method? Please check what
values you have in hostname_resolve table for that host.

**Comment by gautamsomani** [comment]
Hi, thanks for the quick reply. I cannot upgrade the binary, as its in prod, and we use it to monitor around 60 clusters :)

Output of the command is:

2015-07-22 12:58:40 INFO starting
2015-07-22 12:58:40 INFO Read config: /etc/orchestrator.conf.json
2015-07-22 12:58:40 DEBUG Initializing orchestrator
2015-07-22 12:58:40 INFO Starting discovery at {Hostname:flo-oms-db-12 Port:3306}
2015-07-22 12:58:40 DEBUG WriteResolvedHostname: resolved flo-oms-db-12 to flo-oms-db-12.nm.flipkart.com
2015-07-22 12:58:40 DEBUG Discovered host: {Hostname:flo-oms-db-12 Port:3306}, master: {Hostname:flo-oms-db-10 Port:3306}
flo-oms-db-12:3306


Output of table data is:

| hostname                      | resolved_hostname             | resolved_timestamp  |
+-------------------------------+-------------------------------+---------------------+
| flo-oms-db-12                 | flo-oms-db-12.XX.XXXXXXXX.com  | 2015-07-22 12:58:40 |
| flo-oms-db-12.XX.XXXXXXXX.com | flo-oms-db-12.XX.XXXXXXXX.com | 2015-07-22 12:58:54 |

**Comment by gautamsomani** [comment]
So after giving the command, it has come now. I'll upgrade the binary, but any idea what might have gone wrong then?

**Comment by shlomi-noach** [comment]
(have removed sensitive data from your comment)
The hostname_resolve records look just fine (short name resolves to fqdn, fqdn resolves to itself, no surprises there).

If you do a SHOW PROCESSLIST and SHOW SLAVE HOSTS on the master, how does the slave identify itself there? Perhaps it is identified in some other internal name resolution? (unlikely or you would have noticed such entries in hostname_resolve)

**Comment by gautamsomani** [comment]
Show slave hosts will show the ID of the slaves, but the hostname column is blank, which is for all the 7 slaves.

"SHOW PROCESSLIST" shows the complete hostname, the FQDN. From master I did a "host IPADDRESS" and after flushing the dns cache again did a "host FQDN", and both commands worked fine. Same on the host which is running the Orchestrator.

**Comment by shlomi-noach** [comment]
Blank hostname is ignored, so no problem here. Seems like you got it all
sorted out on the SHOW PROCESSLIST -- I don't have any further ideas at
this stage.

**Comment by shlomi-noach** [comment]
I'm going to close this issue unless you are able to reproduce the problem.

**Comment by gautamsomani** [comment]
Not as of now, in case this happens again, will re-open this issue.

Thanks for your support.
